const SONGS = [
  {id:1,title:"Johnny B. Goode",artist:"Chuck Berry",year:1958,q:"Johnny B Goode Chuck Berry"},
  {id:2,title:"Jailhouse Rock",artist:"Elvis Presley",year:1957,q:"Jailhouse Rock Elvis Presley"},
  {id:3,title:"Tutti Frutti",artist:"Little Richard",year:1955,q:"Tutti Frutti Little Richard"},
  {id:4,title:"Rock Around the Clock",artist:"Bill Haley",year:1954,q:"Rock Around the Clock Bill Haley"},
  {id:5,title:"Hound Dog",artist:"Elvis Presley",year:1956,q:"Hound Dog Elvis Presley"},
  {id:6,title:"Great Balls of Fire",artist:"Jerry Lee Lewis",year:1957,q:"Great Balls of Fire Jerry Lee Lewis"},
  {id:7,title:"La Bamba",artist:"Ritchie Valens",year:1958,q:"La Bamba Ritchie Valens"},
  {id:8,title:"What'd I Say",artist:"Ray Charles",year:1959,q:"What I Say Ray Charles"},
  {id:9,title:"Twist and Shout",artist:"The Beatles",year:1963,q:"Twist and Shout Beatles"},
  {id:10,title:"I Want to Hold Your Hand",artist:"The Beatles",year:1963,q:"I Want to Hold Your Hand Beatles"},
  {id:11,title:"Satisfaction",artist:"The Rolling Stones",year:1965,q:"Satisfaction Rolling Stones"},
  {id:12,title:"My Girl",artist:"The Temptations",year:1964,q:"My Girl Temptations"},
  {id:13,title:"Respect",artist:"Aretha Franklin",year:1967,q:"Respect Aretha Franklin"},
  {id:14,title:"Hey Jude",artist:"The Beatles",year:1968,q:"Hey Jude Beatles"},
  {id:15,title:"Like a Rolling Stone",artist:"Bob Dylan",year:1965,q:"Like a Rolling Stone Bob Dylan"},
  {id:16,title:"Good Vibrations",artist:"The Beach Boys",year:1966,q:"Good Vibrations Beach Boys"},
  {id:17,title:"A Whiter Shade of Pale",artist:"Procol Harum",year:1967,q:"Whiter Shade of Pale Procol Harum"},
  {id:18,title:"Somebody to Love",artist:"Jefferson Airplane",year:1967,q:"Somebody to Love Jefferson Airplane"},
  {id:19,title:"Proud Mary",artist:"Creedence Clearwater Revival",year:1969,q:"Proud Mary Creedence Clearwater"},
  {id:20,title:"Come Together",artist:"The Beatles",year:1969,q:"Come Together Beatles"},
  {id:21,title:"Purple Haze",artist:"Jimi Hendrix",year:1967,q:"Purple Haze Jimi Hendrix"},
  {id:22,title:"Stand By Me",artist:"Ben E. King",year:1961,q:"Stand By Me Ben E King"},
  {id:23,title:"The House of the Rising Sun",artist:"The Animals",year:1964,q:"House of the Rising Sun Animals"},
  {id:24,title:"River Deep Mountain High",artist:"Ike & Tina Turner",year:1966,q:"River Deep Mountain High Tina Turner"},
  {id:25,title:"I Heard It Through the Grapevine",artist:"Marvin Gaye",year:1968,q:"Heard It Through Grapevine Marvin Gaye"},
  {id:26,title:"Fortunate Son",artist:"Creedence Clearwater Revival",year:1969,q:"Fortunate Son Creedence"},
  {id:27,title:"Imagine",artist:"John Lennon",year:1971,q:"Imagine John Lennon"},
  {id:28,title:"Stairway to Heaven",artist:"Led Zeppelin",year:1971,q:"Stairway to Heaven Led Zeppelin"},
  {id:29,title:"Superstition",artist:"Stevie Wonder",year:1972,q:"Superstition Stevie Wonder"},
  {id:30,title:"Bohemian Rhapsody",artist:"Queen",year:1975,q:"Bohemian Rhapsody Queen"},
  {id:31,title:"Hotel California",artist:"Eagles",year:1976,q:"Hotel California Eagles"},
  {id:32,title:"Dancing Queen",artist:"ABBA",year:1976,q:"Dancing Queen ABBA"},
  {id:33,title:"Stayin' Alive",artist:"Bee Gees",year:1977,q:"Stayin Alive Bee Gees"},
  {id:34,title:"Rapper's Delight",artist:"Sugarhill Gang",year:1979,q:"Rappers Delight Sugarhill Gang"},
  {id:35,title:"Let It Be",artist:"The Beatles",year:1970,q:"Let It Be Beatles"},
  {id:36,title:"Wish You Were Here",artist:"Pink Floyd",year:1975,q:"Wish You Were Here Pink Floyd"},
  {id:37,title:"Ain't No Sunshine",artist:"Bill Withers",year:1971,q:"Aint No Sunshine Bill Withers"},
  {id:38,title:"Lean on Me",artist:"Bill Withers",year:1972,q:"Lean on Me Bill Withers"},
  {id:39,title:"Let's Stay Together",artist:"Al Green",year:1971,q:"Lets Stay Together Al Green"},
  {id:40,title:"I Will Survive",artist:"Gloria Gaynor",year:1978,q:"I Will Survive Gloria Gaynor"},
  {id:41,title:"We Will Rock You",artist:"Queen",year:1977,q:"We Will Rock You Queen"},
  {id:42,title:"September",artist:"Earth, Wind & Fire",year:1978,q:"September Earth Wind Fire"},
  {id:43,title:"Heart of Glass",artist:"Blondie",year:1978,q:"Heart of Glass Blondie"},
  {id:44,title:"Go Your Own Way",artist:"Fleetwood Mac",year:1977,q:"Go Your Own Way Fleetwood Mac"},
  {id:45,title:"Dreams",artist:"Fleetwood Mac",year:1977,q:"Dreams Fleetwood Mac"},
  {id:46,title:"Waterloo",artist:"ABBA",year:1974,q:"Waterloo ABBA"},
  {id:47,title:"Y.M.C.A.",artist:"Village People",year:1978,q:"YMCA Village People"},
  {id:48,title:"Crocodile Rock",artist:"Elton John",year:1972,q:"Crocodile Rock Elton John"},
  {id:49,title:"Smoke on the Water",artist:"Deep Purple",year:1972,q:"Smoke on the Water Deep Purple"},
  {id:50,title:"Highway to Hell",artist:"AC/DC",year:1979,q:"Highway to Hell ACDC"},
  {id:51,title:"Blitzkrieg Bop",artist:"Ramones",year:1976,q:"Blitzkrieg Bop Ramones"},
  {id:52,title:"London Calling",artist:"The Clash",year:1979,q:"London Calling Clash"},
  {id:53,title:"No Woman No Cry",artist:"Bob Marley",year:1974,q:"No Woman No Cry Bob Marley"},
  {id:54,title:"Kung Fu Fighting",artist:"Carl Douglas",year:1974,q:"Kung Fu Fighting Carl Douglas"},
  {id:55,title:"Play That Funky Music",artist:"Wild Cherry",year:1976,q:"Play That Funky Music Wild Cherry"},
  {id:56,title:"Killing Me Softly",artist:"Roberta Flack",year:1973,q:"Killing Me Softly Roberta Flack"},
  {id:57,title:"Billie Jean",artist:"Michael Jackson",year:1982,q:"Billie Jean Michael Jackson"},
  {id:58,title:"Thriller",artist:"Michael Jackson",year:1982,q:"Thriller Michael Jackson"},
  {id:59,title:"Don't Stop Believin'",artist:"Journey",year:1981,q:"Dont Stop Believin Journey"},
  {id:60,title:"Under Pressure",artist:"Queen & David Bowie",year:1981,q:"Under Pressure Queen Bowie"},
  {id:61,title:"Every Breath You Take",artist:"The Police",year:1983,q:"Every Breath You Take Police"},
  {id:62,title:"Like a Virgin",artist:"Madonna",year:1984,q:"Like a Virgin Madonna"},
  {id:63,title:"Take On Me",artist:"a-ha",year:1985,q:"Take On Me a-ha"},
  {id:64,title:"Sweet Child O' Mine",artist:"Guns N' Roses",year:1987,q:"Sweet Child O Mine Guns N Roses"},
  {id:65,title:"With or Without You",artist:"U2",year:1987,q:"With or Without You U2"},
  {id:66,title:"Livin' on a Prayer",artist:"Bon Jovi",year:1986,q:"Livin on a Prayer Bon Jovi"},
  {id:67,title:"Beat It",artist:"Michael Jackson",year:1982,q:"Beat It Michael Jackson"},
  {id:68,title:"Purple Rain",artist:"Prince",year:1984,q:"Purple Rain Prince"},
  {id:69,title:"When Doves Cry",artist:"Prince",year:1984,q:"When Doves Cry Prince"},
  {id:70,title:"Walk Like an Egyptian",artist:"The Bangles",year:1986,q:"Walk Like an Egyptian Bangles"},
  {id:71,title:"Girls Just Want to Have Fun",artist:"Cyndi Lauper",year:1983,q:"Girls Just Want to Have Fun Cyndi Lauper"},
  {id:72,title:"Jump",artist:"Van Halen",year:1984,q:"Jump Van Halen"},
  {id:73,title:"Tainted Love",artist:"Soft Cell",year:1981,q:"Tainted Love Soft Cell"},
  {id:74,title:"Blue Monday",artist:"New Order",year:1983,q:"Blue Monday New Order"},
  {id:75,title:"Sweet Dreams",artist:"Eurythmics",year:1983,q:"Sweet Dreams Eurythmics"},
  {id:76,title:"Don't You (Forget About Me)",artist:"Simple Minds",year:1985,q:"Dont You Forget About Me Simple Minds"},
  {id:77,title:"Everybody Wants to Rule the World",artist:"Tears for Fears",year:1985,q:"Everybody Wants to Rule the World Tears for Fears"},
  {id:78,title:"Sledgehammer",artist:"Peter Gabriel",year:1986,q:"Sledgehammer Peter Gabriel"},
  {id:79,title:"I Wanna Dance with Somebody",artist:"Whitney Houston",year:1987,q:"I Wanna Dance with Somebody Whitney Houston"},
  {id:80,title:"Faith",artist:"George Michael",year:1987,q:"Faith George Michael"},
  {id:81,title:"Need You Tonight",artist:"INXS",year:1987,q:"Need You Tonight INXS"},
  {id:82,title:"Where the Streets Have No Name",artist:"U2",year:1987,q:"Where the Streets Have No Name U2"},
  {id:83,title:"Enjoy the Silence",artist:"Depeche Mode",year:1990,q:"Enjoy the Silence Depeche Mode"},
  {id:84,title:"Pour Some Sugar on Me",artist:"Def Leppard",year:1987,q:"Pour Some Sugar on Me Def Leppard"},
  {id:85,title:"Welcome to the Jungle",artist:"Guns N' Roses",year:1987,q:"Welcome to the Jungle Guns N Roses"},
  {id:86,title:"The Final Countdown",artist:"Europe",year:1986,q:"Final Countdown Europe"},
  {id:87,title:"Africa",artist:"Toto",year:1982,q:"Africa Toto"},
  {id:88,title:"Don't Stop Me Now",artist:"Queen",year:1978,q:"Dont Stop Me Now Queen"},
  {id:89,title:"Material Girl",artist:"Madonna",year:1984,q:"Material Girl Madonna"},
  {id:90,title:"Eye of the Tiger",artist:"Survivor",year:1982,q:"Eye of the Tiger Survivor"},
  {id:91,title:"Karma Chameleon",artist:"Culture Club",year:1983,q:"Karma Chameleon Culture Club"},
  {id:92,title:"99 Luftballons",artist:"Nena",year:1983,q:"99 Luftballons Nena"},
  {id:93,title:"I Love Rock 'n' Roll",artist:"Joan Jett",year:1981,q:"I Love Rock n Roll Joan Jett"},
  {id:94,title:"Another One Bites the Dust",artist:"Queen",year:1980,q:"Another One Bites the Dust Queen"},
  {id:95,title:"Back in Black",artist:"AC/DC",year:1980,q:"Back in Black ACDC"},
  {id:96,title:"Jessie's Girl",artist:"Rick Springfield",year:1981,q:"Jessies Girl Rick Springfield"},
  {id:97,title:"Never Gonna Give You Up",artist:"Rick Astley",year:1987,q:"Never Gonna Give You Up Rick Astley"},
  {id:98,title:"Smells Like Teen Spirit",artist:"Nirvana",year:1991,q:"Smells Like Teen Spirit Nirvana"},
  {id:99,title:"I Will Always Love You",artist:"Whitney Houston",year:1992,q:"I Will Always Love You Whitney Houston"},
  {id:100,title:"Creep",artist:"Radiohead",year:1992,q:"Creep Radiohead"},
  {id:101,title:"Wonderwall",artist:"Oasis",year:1995,q:"Wonderwall Oasis"},
  {id:102,title:"Gangsta's Paradise",artist:"Coolio",year:1995,q:"Gangsta Paradise Coolio"},
  {id:103,title:"Say My Name",artist:"Destiny's Child",year:1999,q:"Say My Name Destinys Child"},
  {id:104,title:"Waterfalls",artist:"TLC",year:1994,q:"Waterfalls TLC"},
  {id:105,title:"No Scrubs",artist:"TLC",year:1999,q:"No Scrubs TLC"},
  {id:106,title:"Black Hole Sun",artist:"Soundgarden",year:1994,q:"Black Hole Sun Soundgarden"},
  {id:107,title:"Jeremy",artist:"Pearl Jam",year:1991,q:"Jeremy Pearl Jam"},
  {id:108,title:"Under the Bridge",artist:"Red Hot Chili Peppers",year:1991,q:"Under the Bridge Red Hot Chili Peppers"},
  {id:109,title:"Losing My Religion",artist:"R.E.M.",year:1991,q:"Losing My Religion REM"},
  {id:110,title:"One",artist:"U2",year:1991,q:"One U2"},
  {id:111,title:"Nothing Compares 2 U",artist:"Sinead O'Connor",year:1990,q:"Nothing Compares 2 U Sinead"},
  {id:112,title:"Vogue",artist:"Madonna",year:1990,q:"Vogue Madonna"},
  {id:113,title:"Jump Around",artist:"House of Pain",year:1992,q:"Jump Around House of Pain"},
  {id:114,title:"Baby One More Time",artist:"Britney Spears",year:1998,q:"Baby One More Time Britney Spears"},
  {id:115,title:"Wannabe",artist:"Spice Girls",year:1996,q:"Wannabe Spice Girls"},
  {id:116,title:"MMMBop",artist:"Hanson",year:1997,q:"MMMBop Hanson"},
  {id:117,title:"Iris",artist:"Goo Goo Dolls",year:1998,q:"Iris Goo Goo Dolls"},
  {id:118,title:"Bitter Sweet Symphony",artist:"The Verve",year:1997,q:"Bitter Sweet Symphony Verve"},
  {id:119,title:"Tearin' Up My Heart",artist:"NSYNC",year:1997,q:"Tearin Up My Heart NSYNC"},
  {id:120,title:"I Want It That Way",artist:"Backstreet Boys",year:1999,q:"I Want It That Way Backstreet Boys"},
  {id:121,title:"Tubthumping",artist:"Chumbawamba",year:1997,q:"Tubthumping Chumbawamba"},
  {id:122,title:"Zombie",artist:"The Cranberries",year:1994,q:"Zombie Cranberries"},
  {id:123,title:"Dream On",artist:"Aerosmith",year:1993,q:"Dream On Aerosmith"},
  {id:124,title:"Doo Wop (That Thing)",artist:"Lauryn Hill",year:1998,q:"Doo Wop That Thing Lauryn Hill"},
  {id:125,title:"California Love",artist:"2Pac",year:1995,q:"California Love 2Pac"},
  {id:126,title:"Hypnotize",artist:"Notorious B.I.G.",year:1997,q:"Hypnotize Notorious BIG"},
  {id:127,title:"My Name Is",artist:"Eminem",year:1999,q:"My Name Is Eminem"},
  {id:128,title:"No Diggity",artist:"Blackstreet",year:1996,q:"No Diggity Blackstreet"},
  {id:129,title:"Basket Case",artist:"Green Day",year:1994,q:"Basket Case Green Day"},
  {id:130,title:"Today",artist:"Smashing Pumpkins",year:1993,q:"Today Smashing Pumpkins"},
  {id:131,title:"Creep",artist:"TLC",year:1994,q:"Creep TLC"},
  {id:132,title:"Buddy Holly",artist:"Weezer",year:1994,q:"Buddy Holly Weezer"},
  {id:133,title:"Return of the Mack",artist:"Mark Morrison",year:1996,q:"Return of the Mack Mark Morrison"},
  {id:134,title:"Mo Money Mo Problems",artist:"Notorious B.I.G.",year:1997,q:"Mo Money Mo Problems Notorious"},
  {id:135,title:"Smooth",artist:"Santana ft. Rob Thomas",year:1999,q:"Smooth Santana Rob Thomas"},
  {id:136,title:"All Star",artist:"Smash Mouth",year:1999,q:"All Star Smash Mouth"},
  {id:137,title:"Livin' La Vida Loca",artist:"Ricky Martin",year:1999,q:"Livin La Vida Loca Ricky Martin"},
  {id:138,title:"Torn",artist:"Natalie Imbruglia",year:1997,q:"Torn Natalie Imbruglia"},
  {id:139,title:"Believe",artist:"Cher",year:1998,q:"Believe Cher"},
  {id:140,title:"Kiss from a Rose",artist:"Seal",year:1994,q:"Kiss from a Rose Seal"},
  {id:141,title:"Semi-Charmed Life",artist:"Third Eye Blind",year:1997,q:"Semi Charmed Life Third Eye Blind"},
  {id:142,title:"Barbie Girl",artist:"Aqua",year:1997,q:"Barbie Girl Aqua"},
  {id:143,title:"Lose Yourself",artist:"Eminem",year:2002,q:"Lose Yourself Eminem"},
  {id:144,title:"Crazy in Love",artist:"Beyoncé",year:2003,q:"Crazy in Love Beyonce"},
  {id:145,title:"Mr. Brightside",artist:"The Killers",year:2003,q:"Mr Brightside Killers"},
  {id:146,title:"In Da Club",artist:"50 Cent",year:2003,q:"In Da Club 50 Cent"},
  {id:147,title:"Toxic",artist:"Britney Spears",year:2003,q:"Toxic Britney Spears"},
  {id:148,title:"Umbrella",artist:"Rihanna",year:2007,q:"Umbrella Rihanna"},
  {id:149,title:"Poker Face",artist:"Lady Gaga",year:2008,q:"Poker Face Lady Gaga"},
  {id:150,title:"Hey Ya!",artist:"OutKast",year:2003,q:"Hey Ya OutKast"},
  {id:151,title:"Complicated",artist:"Avril Lavigne",year:2002,q:"Complicated Avril Lavigne"},
  {id:152,title:"In the End",artist:"Linkin Park",year:2000,q:"In the End Linkin Park"},
  {id:153,title:"Numb",artist:"Linkin Park",year:2003,q:"Numb Linkin Park"},
  {id:154,title:"Boulevard of Broken Dreams",artist:"Green Day",year:2004,q:"Boulevard of Broken Dreams Green Day"},
  {id:155,title:"Clocks",artist:"Coldplay",year:2002,q:"Clocks Coldplay"},
  {id:156,title:"The Scientist",artist:"Coldplay",year:2002,q:"The Scientist Coldplay"},
  {id:157,title:"Hips Don't Lie",artist:"Shakira",year:2006,q:"Hips Dont Lie Shakira"},
  {id:158,title:"SOS",artist:"Rihanna",year:2006,q:"SOS Rihanna"},
  {id:159,title:"Gold Digger",artist:"Kanye West",year:2005,q:"Gold Digger Kanye West"},
  {id:160,title:"Stronger",artist:"Kanye West",year:2007,q:"Stronger Kanye West"},
  {id:161,title:"Rehab",artist:"Amy Winehouse",year:2006,q:"Rehab Amy Winehouse"},
  {id:162,title:"Chasing Cars",artist:"Snow Patrol",year:2006,q:"Chasing Cars Snow Patrol"},
  {id:163,title:"Crazy",artist:"Gnarls Barkley",year:2006,q:"Crazy Gnarls Barkley"},
  {id:164,title:"Use Somebody",artist:"Kings of Leon",year:2008,q:"Use Somebody Kings of Leon"},
  {id:165,title:"Single Ladies",artist:"Beyoncé",year:2008,q:"Single Ladies Beyonce"},
  {id:166,title:"Viva la Vida",artist:"Coldplay",year:2008,q:"Viva la Vida Coldplay"},
  {id:167,title:"Apologize",artist:"OneRepublic",year:2007,q:"Apologize OneRepublic"},
  {id:168,title:"Seven Nation Army",artist:"The White Stripes",year:2003,q:"Seven Nation Army White Stripes"},
  {id:169,title:"Feel Good Inc.",artist:"Gorillaz",year:2005,q:"Feel Good Inc Gorillaz"},
  {id:170,title:"Since U Been Gone",artist:"Kelly Clarkson",year:2004,q:"Since U Been Gone Kelly Clarkson"},
  {id:171,title:"Beautiful Day",artist:"U2",year:2000,q:"Beautiful Day U2"},
  {id:172,title:"Bye Bye Bye",artist:"NSYNC",year:2000,q:"Bye Bye Bye NSYNC"},
  {id:173,title:"Stan",artist:"Eminem",year:2000,q:"Stan Eminem"},
  {id:174,title:"Yeah!",artist:"Usher",year:2004,q:"Yeah Usher"},
  {id:175,title:"Drop It Like It's Hot",artist:"Snoop Dogg",year:2004,q:"Drop It Like Its Hot Snoop Dogg"},
  {id:176,title:"Ignition (Remix)",artist:"R. Kelly",year:2003,q:"Ignition Remix R Kelly"},
  {id:177,title:"Hung Up",artist:"Madonna",year:2005,q:"Hung Up Madonna"},
  {id:178,title:"Candy Shop",artist:"50 Cent",year:2005,q:"Candy Shop 50 Cent"},
  {id:179,title:"Paper Planes",artist:"M.I.A.",year:2007,q:"Paper Planes MIA"},
  {id:180,title:"Bleeding Love",artist:"Leona Lewis",year:2007,q:"Bleeding Love Leona Lewis"},
  {id:181,title:"I Gotta Feeling",artist:"Black Eyed Peas",year:2009,q:"I Gotta Feeling Black Eyed Peas"},
  {id:182,title:"Boom Boom Pow",artist:"Black Eyed Peas",year:2009,q:"Boom Boom Pow Black Eyed Peas"},
  {id:183,title:"Just Dance",artist:"Lady Gaga",year:2008,q:"Just Dance Lady Gaga"},
  {id:184,title:"Disturbia",artist:"Rihanna",year:2008,q:"Disturbia Rihanna"},
  {id:185,title:"Lollipop",artist:"Lil Wayne",year:2008,q:"Lollipop Lil Wayne"},
  {id:186,title:"Low",artist:"Flo Rida",year:2007,q:"Low Flo Rida"},
  {id:187,title:"Crank That",artist:"Soulja Boy",year:2007,q:"Crank That Soulja Boy"},
  {id:188,title:"Rolling in the Deep",artist:"Adele",year:2010,q:"Rolling in the Deep Adele"},
  {id:189,title:"Somebody That I Used to Know",artist:"Gotye",year:2011,q:"Somebody That I Used to Know Gotye"},
  {id:190,title:"Get Lucky",artist:"Daft Punk",year:2013,q:"Get Lucky Daft Punk"},
  {id:191,title:"Uptown Funk",artist:"Bruno Mars",year:2014,q:"Uptown Funk Bruno Mars"},
  {id:192,title:"Shape of You",artist:"Ed Sheeran",year:2017,q:"Shape of You Ed Sheeran"},
  {id:193,title:"Blinding Lights",artist:"The Weeknd",year:2019,q:"Blinding Lights Weeknd"},
  {id:194,title:"Old Town Road",artist:"Lil Nas X",year:2019,q:"Old Town Road Lil Nas X"},
  {id:195,title:"Someone Like You",artist:"Adele",year:2011,q:"Someone Like You Adele"},
  {id:196,title:"Call Me Maybe",artist:"Carly Rae Jepsen",year:2012,q:"Call Me Maybe Carly Rae Jepsen"},
  {id:197,title:"Gangnam Style",artist:"PSY",year:2012,q:"Gangnam Style PSY"},
  {id:198,title:"Royals",artist:"Lorde",year:2013,q:"Royals Lorde"},
  {id:199,title:"Happy",artist:"Pharrell Williams",year:2013,q:"Happy Pharrell Williams"},
  {id:200,title:"Thinking Out Loud",artist:"Ed Sheeran",year:2014,q:"Thinking Out Loud Ed Sheeran"},
  {id:201,title:"All About That Bass",artist:"Meghan Trainor",year:2014,q:"All About That Bass Meghan Trainor"},
  {id:202,title:"Shake It Off",artist:"Taylor Swift",year:2014,q:"Shake It Off Taylor Swift"},
  {id:203,title:"Blank Space",artist:"Taylor Swift",year:2014,q:"Blank Space Taylor Swift"},
  {id:204,title:"Hello",artist:"Adele",year:2015,q:"Hello Adele"},
  {id:205,title:"Sorry",artist:"Justin Bieber",year:2015,q:"Sorry Justin Bieber"},
  {id:206,title:"Can't Feel My Face",artist:"The Weeknd",year:2015,q:"Cant Feel My Face Weeknd"},
  {id:207,title:"Hotline Bling",artist:"Drake",year:2015,q:"Hotline Bling Drake"},
  {id:208,title:"Work",artist:"Rihanna",year:2016,q:"Work Rihanna"},
  {id:209,title:"Cheap Thrills",artist:"Sia",year:2016,q:"Cheap Thrills Sia"},
  {id:210,title:"Closer",artist:"The Chainsmokers",year:2016,q:"Closer Chainsmokers"},
  {id:211,title:"Stressed Out",artist:"Twenty One Pilots",year:2015,q:"Stressed Out Twenty One Pilots"},
  {id:212,title:"Despacito",artist:"Luis Fonsi",year:2017,q:"Despacito Luis Fonsi"},
  {id:213,title:"Havana",artist:"Camila Cabello",year:2017,q:"Havana Camila Cabello"},
  {id:214,title:"Humble",artist:"Kendrick Lamar",year:2017,q:"Humble Kendrick Lamar"},
  {id:215,title:"God's Plan",artist:"Drake",year:2018,q:"Gods Plan Drake"},
  {id:216,title:"Thank U, Next",artist:"Ariana Grande",year:2018,q:"Thank U Next Ariana Grande"},
  {id:217,title:"Shallow",artist:"Lady Gaga & Bradley Cooper",year:2018,q:"Shallow Lady Gaga Bradley Cooper"},
  {id:218,title:"Sunflower",artist:"Post Malone",year:2018,q:"Sunflower Post Malone"},
  {id:219,title:"Bad Guy",artist:"Billie Eilish",year:2019,q:"Bad Guy Billie Eilish"},
  {id:220,title:"Señorita",artist:"Shawn Mendes & Camila Cabello",year:2019,q:"Senorita Shawn Mendes Camila Cabello"},
  {id:221,title:"Truth Hurts",artist:"Lizzo",year:2019,q:"Truth Hurts Lizzo"},
  {id:222,title:"Don't Start Now",artist:"Dua Lipa",year:2019,q:"Dont Start Now Dua Lipa"},
  {id:223,title:"Taki Taki",artist:"DJ Snake ft. Selena Gomez",year:2018,q:"Taki Taki DJ Snake Selena Gomez"},
  {id:224,title:"Starboy",artist:"The Weeknd",year:2016,q:"Starboy Weeknd"},
  {id:225,title:"Rockstar",artist:"Post Malone",year:2017,q:"Rockstar Post Malone"},
  {id:226,title:"Something Just Like This",artist:"Chainsmokers & Coldplay",year:2017,q:"Something Just Like This Chainsmokers Coldplay"},
  {id:227,title:"Thunder",artist:"Imagine Dragons",year:2017,q:"Thunder Imagine Dragons"},
  {id:228,title:"Radioactive",artist:"Imagine Dragons",year:2012,q:"Radioactive Imagine Dragons"},
  {id:229,title:"Counting Stars",artist:"OneRepublic",year:2013,q:"Counting Stars OneRepublic"},
  {id:230,title:"Chandelier",artist:"Sia",year:2014,q:"Chandelier Sia"},
  {id:231,title:"Stitches",artist:"Shawn Mendes",year:2015,q:"Stitches Shawn Mendes"},
  {id:232,title:"Love Yourself",artist:"Justin Bieber",year:2015,q:"Love Yourself Justin Bieber"},
  {id:233,title:"One Dance",artist:"Drake",year:2016,q:"One Dance Drake"},
  {id:234,title:"Lean On",artist:"Major Lazer & DJ Snake",year:2015,q:"Lean On Major Lazer"},
  {id:235,title:"Take Me to Church",artist:"Hozier",year:2013,q:"Take Me to Church Hozier"},
  {id:236,title:"Stay with Me",artist:"Sam Smith",year:2014,q:"Stay with Me Sam Smith"},
  {id:237,title:"Pumped Up Kicks",artist:"Foster the People",year:2010,q:"Pumped Up Kicks Foster the People"},
  {id:238,title:"We Found Love",artist:"Rihanna",year:2011,q:"We Found Love Rihanna"},
  {id:239,title:"Titanium",artist:"David Guetta ft. Sia",year:2011,q:"Titanium David Guetta Sia"},
  {id:240,title:"Levels",artist:"Avicii",year:2011,q:"Levels Avicii"},
  {id:241,title:"Wake Me Up",artist:"Avicii",year:2013,q:"Wake Me Up Avicii"},
  {id:242,title:"Locked Out of Heaven",artist:"Bruno Mars",year:2012,q:"Locked Out of Heaven Bruno Mars"},
  {id:243,title:"When I Was Your Man",artist:"Bruno Mars",year:2013,q:"When I Was Your Man Bruno Mars"},
  {id:244,title:"Wrecking Ball",artist:"Miley Cyrus",year:2013,q:"Wrecking Ball Miley Cyrus"},
  {id:245,title:"Thrift Shop",artist:"Macklemore",year:2012,q:"Thrift Shop Macklemore"},
  {id:246,title:"Riptide",artist:"Vance Joy",year:2013,q:"Riptide Vance Joy"},
  {id:247,title:"Let Her Go",artist:"Passenger",year:2012,q:"Let Her Go Passenger"},
  {id:248,title:"Timber",artist:"Pitbull ft. Kesha",year:2013,q:"Timber Pitbull Kesha"},
  {id:249,title:"Dark Horse",artist:"Katy Perry",year:2013,q:"Dark Horse Katy Perry"},
  {id:250,title:"Roar",artist:"Katy Perry",year:2013,q:"Roar Katy Perry"},
  {id:251,title:"Firework",artist:"Katy Perry",year:2010,q:"Firework Katy Perry"},
  {id:252,title:"Teenage Dream",artist:"Katy Perry",year:2010,q:"Teenage Dream Katy Perry"},
  {id:253,title:"Born This Way",artist:"Lady Gaga",year:2011,q:"Born This Way Lady Gaga"},
  {id:254,title:"Party Rock Anthem",artist:"LMFAO",year:2011,q:"Party Rock Anthem LMFAO"},
  {id:255,title:"Moves Like Jagger",artist:"Maroon 5",year:2011,q:"Moves Like Jagger Maroon 5"},
  {id:256,title:"Payphone",artist:"Maroon 5",year:2012,q:"Payphone Maroon 5"},
  {id:257,title:"Sucker",artist:"Jonas Brothers",year:2019,q:"Sucker Jonas Brothers"},
  {id:258,title:"7 Rings",artist:"Ariana Grande",year:2019,q:"7 Rings Ariana Grande"},
  {id:259,title:"As It Was",artist:"Harry Styles",year:2022,q:"As It Was Harry Styles"},
  {id:260,title:"Watermelon Sugar",artist:"Harry Styles",year:2020,q:"Watermelon Sugar Harry Styles"},
  {id:261,title:"Levitating",artist:"Dua Lipa",year:2020,q:"Levitating Dua Lipa"},
  {id:262,title:"drivers license",artist:"Olivia Rodrigo",year:2021,q:"drivers license Olivia Rodrigo"},
  {id:263,title:"good 4 u",artist:"Olivia Rodrigo",year:2021,q:"good 4 u Olivia Rodrigo"},
  {id:264,title:"Stay",artist:"The Kid LAROI & Justin Bieber",year:2021,q:"Stay Kid LAROI Justin Bieber"},
  {id:265,title:"Montero",artist:"Lil Nas X",year:2021,q:"Montero Lil Nas X"},
  {id:266,title:"Peaches",artist:"Justin Bieber",year:2021,q:"Peaches Justin Bieber"},
  {id:267,title:"Save Your Tears",artist:"The Weeknd",year:2020,q:"Save Your Tears Weeknd"},
  {id:268,title:"Dynamite",artist:"BTS",year:2020,q:"Dynamite BTS"},
  {id:269,title:"positions",artist:"Ariana Grande",year:2020,q:"positions Ariana Grande"},
  {id:270,title:"Savage Love",artist:"Jawsh 685 & Jason Derulo",year:2020,q:"Savage Love Jason Derulo"},
  {id:271,title:"Heat Waves",artist:"Glass Animals",year:2020,q:"Heat Waves Glass Animals"},
  {id:272,title:"Butter",artist:"BTS",year:2021,q:"Butter BTS"},
  {id:273,title:"Kiss Me More",artist:"Doja Cat ft. SZA",year:2021,q:"Kiss Me More Doja Cat SZA"},
  {id:274,title:"Industry Baby",artist:"Lil Nas X & Jack Harlow",year:2021,q:"Industry Baby Lil Nas X"},
  {id:275,title:"Easy on Me",artist:"Adele",year:2021,q:"Easy on Me Adele"},
  {id:276,title:"abcdefu",artist:"GAYLE",year:2021,q:"abcdefu GAYLE"},
  {id:277,title:"About Damn Time",artist:"Lizzo",year:2022,q:"About Damn Time Lizzo"},
  {id:278,title:"Anti-Hero",artist:"Taylor Swift",year:2022,q:"Anti Hero Taylor Swift"},
  {id:279,title:"Unholy",artist:"Sam Smith & Kim Petras",year:2022,q:"Unholy Sam Smith Kim Petras"},
  {id:280,title:"Running Up That Hill",artist:"Kate Bush",year:1985,q:"Running Up That Hill Kate Bush"},
  {id:281,title:"Flowers",artist:"Miley Cyrus",year:2023,q:"Flowers Miley Cyrus"},
  {id:282,title:"Kill Bill",artist:"SZA",year:2022,q:"Kill Bill SZA"},
  {id:283,title:"Vampire",artist:"Olivia Rodrigo",year:2023,q:"Vampire Olivia Rodrigo"},
  {id:284,title:"Cruel Summer",artist:"Taylor Swift",year:2019,q:"Cruel Summer Taylor Swift"},
  {id:285,title:"Espresso",artist:"Sabrina Carpenter",year:2024,q:"Espresso Sabrina Carpenter"},
  {id:286,title:"Lovin on Me",artist:"Jack Harlow",year:2023,q:"Lovin on Me Jack Harlow"},
  {id:287,title:"Paint the Town Red",artist:"Doja Cat",year:2023,q:"Paint the Town Red Doja Cat"},
  {id:288,title:"Snooze",artist:"SZA",year:2022,q:"Snooze SZA"},
  {id:289,title:"Peggy Sue",artist:"Buddy Holly",year:1957,q:"Peggy Sue Buddy Holly"},
  {id:290,title:"That'll Be the Day",artist:"Buddy Holly",year:1957,q:"Thatll Be the Day Buddy Holly"},
  {id:291,title:"Whole Lotta Shakin' Goin' On",artist:"Jerry Lee Lewis",year:1957,q:"Whole Lotta Shakin Goin On Jerry Lee Lewis"},
  {id:292,title:"Blueberry Hill",artist:"Fats Domino",year:1956,q:"Blueberry Hill Fats Domino"},
  {id:293,title:"Shake, Rattle and Roll",artist:"Big Joe Turner",year:1954,q:"Shake Rattle and Roll Big Joe Turner"},
  {id:294,title:"Only You",artist:"The Platters",year:1955,q:"Only You Platters"},
  {id:295,title:"Unchained Melody",artist:"The Righteous Brothers",year:1955,q:"Unchained Melody Righteous Brothers"},
  {id:296,title:"Paint It Black",artist:"The Rolling Stones",year:1966,q:"Paint It Black Rolling Stones"},
  {id:297,title:"Sympathy for the Devil",artist:"The Rolling Stones",year:1968,q:"Sympathy for the Devil Rolling Stones"},
  {id:298,title:"Light My Fire",artist:"The Doors",year:1967,q:"Light My Fire Doors"},
  {id:299,title:"Riders on the Storm",artist:"The Doors",year:1971,q:"Riders on the Storm Doors"},
  {id:300,title:"All Along the Watchtower",artist:"Jimi Hendrix",year:1968,q:"All Along the Watchtower Jimi Hendrix"},
  {id:301,title:"You Really Got Me",artist:"The Kinks",year:1964,q:"You Really Got Me Kinks"},
  {id:302,title:"Mrs. Robinson",artist:"Simon & Garfunkel",year:1968,q:"Mrs Robinson Simon Garfunkel"},
  {id:303,title:"The Sound of Silence",artist:"Simon & Garfunkel",year:1965,q:"Sound of Silence Simon Garfunkel"},
  {id:304,title:"Bridge Over Troubled Water",artist:"Simon & Garfunkel",year:1970,q:"Bridge Over Troubled Water Simon Garfunkel"},
  {id:305,title:"Yesterday",artist:"The Beatles",year:1965,q:"Yesterday Beatles"},
  {id:306,title:"Here Comes the Sun",artist:"The Beatles",year:1969,q:"Here Comes the Sun Beatles"},
  {id:307,title:"California Dreamin'",artist:"The Mamas & The Papas",year:1965,q:"California Dreamin Mamas Papas"},
  {id:308,title:"These Boots Are Made for Walkin'",artist:"Nancy Sinatra",year:1966,q:"These Boots Are Made for Walkin Nancy Sinatra"},
  {id:309,title:"Born to Be Wild",artist:"Steppenwolf",year:1968,q:"Born to Be Wild Steppenwolf"},
  {id:310,title:"Gimme Shelter",artist:"The Rolling Stones",year:1969,q:"Gimme Shelter Rolling Stones"},
  {id:311,title:"For What It's Worth",artist:"Buffalo Springfield",year:1966,q:"For What Its Worth Buffalo Springfield"},
  {id:312,title:"White Rabbit",artist:"Jefferson Airplane",year:1967,q:"White Rabbit Jefferson Airplane"},
  {id:313,title:"Soul Man",artist:"Sam & Dave",year:1967,q:"Soul Man Sam Dave"},
  {id:314,title:"People Get Ready",artist:"The Impressions",year:1965,q:"People Get Ready Impressions"},
  {id:315,title:"Bohemian Like You",artist:"The Dandy Warhols",year:2000,q:"Bohemian Like You Dandy Warhols"},
  {id:316,title:"Tiny Dancer",artist:"Elton John",year:1971,q:"Tiny Dancer Elton John"},
  {id:317,title:"Your Song",artist:"Elton John",year:1970,q:"Your Song Elton John"},
  {id:318,title:"Rocket Man",artist:"Elton John",year:1972,q:"Rocket Man Elton John"},
  {id:319,title:"Bennie and the Jets",artist:"Elton John",year:1973,q:"Bennie and the Jets Elton John"},
  {id:320,title:"Free Bird",artist:"Lynyrd Skynyrd",year:1973,q:"Free Bird Lynyrd Skynyrd"},
  {id:321,title:"Sweet Home Alabama",artist:"Lynyrd Skynyrd",year:1974,q:"Sweet Home Alabama Lynyrd Skynyrd"},
  {id:322,title:"Night Fever",artist:"Bee Gees",year:1977,q:"Night Fever Bee Gees"},
  {id:323,title:"How Deep Is Your Love",artist:"Bee Gees",year:1977,q:"How Deep Is Your Love Bee Gees"},
  {id:324,title:"Dust in the Wind",artist:"Kansas",year:1977,q:"Dust in the Wind Kansas"},
  {id:325,title:"More Than a Feeling",artist:"Boston",year:1976,q:"More Than a Feeling Boston"},
  {id:326,title:"Barracuda",artist:"Heart",year:1977,q:"Barracuda Heart"},
  {id:327,title:"Walk This Way",artist:"Aerosmith",year:1975,q:"Walk This Way Aerosmith"},
  {id:328,title:"Black Dog",artist:"Led Zeppelin",year:1971,q:"Black Dog Led Zeppelin"},
  {id:329,title:"Whole Lotta Love",artist:"Led Zeppelin",year:1969,q:"Whole Lotta Love Led Zeppelin"},
  {id:330,title:"Paranoid",artist:"Black Sabbath",year:1970,q:"Paranoid Black Sabbath"},
  {id:331,title:"Iron Man",artist:"Black Sabbath",year:1970,q:"Iron Man Black Sabbath"},
  {id:332,title:"Comfortably Numb",artist:"Pink Floyd",year:1979,q:"Comfortably Numb Pink Floyd"},
  {id:333,title:"Another Brick in the Wall",artist:"Pink Floyd",year:1979,q:"Another Brick in the Wall Pink Floyd"},
  {id:334,title:"Money",artist:"Pink Floyd",year:1973,q:"Money Pink Floyd"},
  {id:335,title:"Roxanne",artist:"The Police",year:1978,q:"Roxanne Police"},
  {id:336,title:"Carry On Wayward Son",artist:"Kansas",year:1976,q:"Carry On Wayward Son Kansas"},
  {id:337,title:"Don't Fear the Reaper",artist:"Blue Öyster Cult",year:1976,q:"Dont Fear the Reaper Blue Oyster Cult"},
  {id:338,title:"Born to Run",artist:"Bruce Springsteen",year:1975,q:"Born to Run Bruce Springsteen"},
  {id:339,title:"Thunder Road",artist:"Bruce Springsteen",year:1975,q:"Thunder Road Bruce Springsteen"},
  {id:340,title:"Landslide",artist:"Fleetwood Mac",year:1975,q:"Landslide Fleetwood Mac"},
  {id:341,title:"Sultans of Swing",artist:"Dire Straits",year:1978,q:"Sultans of Swing Dire Straits"},
  {id:342,title:"We Are the Champions",artist:"Queen",year:1977,q:"We Are the Champions Queen"},
  {id:343,title:"Dancing in the Moonlight",artist:"King Harvest",year:1972,q:"Dancing in the Moonlight King Harvest"},
  {id:344,title:"Boogie Wonderland",artist:"Earth, Wind & Fire",year:1979,q:"Boogie Wonderland Earth Wind Fire"},
  {id:345,title:"Le Freak",artist:"Chic",year:1978,q:"Le Freak Chic"},
  {id:346,title:"Good Times",artist:"Chic",year:1979,q:"Good Times Chic"},
  {id:347,title:"Ring My Bell",artist:"Anita Ward",year:1979,q:"Ring My Bell Anita Ward"},
  {id:348,title:"Car Wash",artist:"Rose Royce",year:1976,q:"Car Wash Rose Royce"},
  {id:349,title:"Take My Breath Away",artist:"Berlin",year:1986,q:"Take My Breath Away Berlin"},
  {id:350,title:"Danger Zone",artist:"Kenny Loggins",year:1986,q:"Danger Zone Kenny Loggins"},
  {id:351,title:"Footloose",artist:"Kenny Loggins",year:1984,q:"Footloose Kenny Loggins"},
  {id:352,title:"Ghostbusters",artist:"Ray Parker Jr.",year:1984,q:"Ghostbusters Ray Parker Jr"},
  {id:353,title:"Maniac",artist:"Michael Sembello",year:1983,q:"Maniac Michael Sembello"},
  {id:354,title:"Flashdance... What a Feeling",artist:"Irene Cara",year:1983,q:"Flashdance What a Feeling Irene Cara"},
  {id:355,title:"Total Eclipse of the Heart",artist:"Bonnie Tyler",year:1983,q:"Total Eclipse of the Heart Bonnie Tyler"},
  {id:356,title:"Time After Time",artist:"Cyndi Lauper",year:1983,q:"Time After Time Cyndi Lauper"},
  {id:357,title:"I Ran (So Far Away)",artist:"A Flock of Seagulls",year:1982,q:"I Ran So Far Away Flock of Seagulls"},
  {id:358,title:"Come On Eileen",artist:"Dexys Midnight Runners",year:1982,q:"Come On Eileen Dexys Midnight Runners"},
  {id:359,title:"Down Under",artist:"Men at Work",year:1981,q:"Down Under Men at Work"},
  {id:360,title:"Personal Jesus",artist:"Depeche Mode",year:1989,q:"Personal Jesus Depeche Mode"},
  {id:361,title:"Just Like Heaven",artist:"The Cure",year:1987,q:"Just Like Heaven Cure"},
  {id:362,title:"Lovesong",artist:"The Cure",year:1989,q:"Lovesong Cure"},
  {id:363,title:"Once in a Lifetime",artist:"Talking Heads",year:1980,q:"Once in a Lifetime Talking Heads"},
  {id:364,title:"Psycho Killer",artist:"Talking Heads",year:1977,q:"Psycho Killer Talking Heads"},
  {id:365,title:"Love Will Tear Us Apart",artist:"Joy Division",year:1980,q:"Love Will Tear Us Apart Joy Division"},
  {id:366,title:"Bizarre Love Triangle",artist:"New Order",year:1986,q:"Bizarre Love Triangle New Order"},
  {id:367,title:"West End Girls",artist:"Pet Shop Boys",year:1985,q:"West End Girls Pet Shop Boys"},
  {id:368,title:"Shout",artist:"Tears for Fears",year:1984,q:"Shout Tears for Fears"},
  {id:369,title:"Careless Whisper",artist:"George Michael",year:1984,q:"Careless Whisper George Michael"},
  {id:370,title:"Wake Me Up Before You Go-Go",artist:"Wham!",year:1984,q:"Wake Me Up Before You Go Go Wham"},
  {id:371,title:"Last Christmas",artist:"Wham!",year:1984,q:"Last Christmas Wham"},
  {id:372,title:"The Power of Love",artist:"Huey Lewis",year:1985,q:"Power of Love Huey Lewis"},
  {id:373,title:"Alive and Kicking",artist:"Simple Minds",year:1985,q:"Alive and Kicking Simple Minds"},
  {id:374,title:"In the Air Tonight",artist:"Phil Collins",year:1981,q:"In the Air Tonight Phil Collins"},
  {id:375,title:"Against All Odds",artist:"Phil Collins",year:1984,q:"Against All Odds Phil Collins"},
  {id:376,title:"Hungry Like the Wolf",artist:"Duran Duran",year:1982,q:"Hungry Like the Wolf Duran Duran"},
  {id:377,title:"Rio",artist:"Duran Duran",year:1982,q:"Rio Duran Duran"},
  {id:378,title:"Money for Nothing",artist:"Dire Straits",year:1985,q:"Money for Nothing Dire Straits"},
  {id:379,title:"Brothers in Arms",artist:"Dire Straits",year:1985,q:"Brothers in Arms Dire Straits"},
  {id:380,title:"Under the Milky Way",artist:"The Church",year:1988,q:"Under the Milky Way Church"},
  {id:381,title:"Stripped",artist:"Depeche Mode",year:1986,q:"Stripped Depeche Mode"},
  {id:382,title:"Maneater",artist:"Hall & Oates",year:1982,q:"Maneater Hall Oates"},
  {id:383,title:"867-5309/Jenny",artist:"Tommy Tutone",year:1981,q:"867 5309 Jenny Tommy Tutone"},
  {id:384,title:"Our House",artist:"Madness",year:1982,q:"Our House Madness"},
  {id:385,title:"Relax",artist:"Frankie Goes to Hollywood",year:1983,q:"Relax Frankie Goes to Hollywood"},
  {id:386,title:"Owner of a Lonely Heart",artist:"Yes",year:1983,q:"Owner of a Lonely Heart Yes"},
  {id:387,title:"Born in the U.S.A.",artist:"Bruce Springsteen",year:1984,q:"Born in the USA Bruce Springsteen"},
  {id:388,title:"Dancing in the Dark",artist:"Bruce Springsteen",year:1984,q:"Dancing in the Dark Bruce Springsteen"},
  {id:389,title:"Heart-Shaped Box",artist:"Nirvana",year:1993,q:"Heart Shaped Box Nirvana"},
  {id:390,title:"Alive",artist:"Pearl Jam",year:1991,q:"Alive Pearl Jam"},
  {id:391,title:"Even Flow",artist:"Pearl Jam",year:1991,q:"Even Flow Pearl Jam"},
  {id:392,title:"Plush",artist:"Stone Temple Pilots",year:1992,q:"Plush Stone Temple Pilots"},
  {id:393,title:"Man in the Box",artist:"Alice in Chains",year:1990,q:"Man in the Box Alice in Chains"},
  {id:394,title:"Would?",artist:"Alice in Chains",year:1992,q:"Would Alice in Chains"},
  {id:395,title:"Give It Away",artist:"Red Hot Chili Peppers",year:1991,q:"Give It Away Red Hot Chili Peppers"},
  {id:396,title:"Scar Tissue",artist:"Red Hot Chili Peppers",year:1999,q:"Scar Tissue Red Hot Chili Peppers"},
  {id:397,title:"Glycerine",artist:"Bush",year:1994,q:"Glycerine Bush"},
  {id:398,title:"No Rain",artist:"Blind Melon",year:1992,q:"No Rain Blind Melon"},
  {id:399,title:"Mmm Mmm Mmm Mmm",artist:"Crash Test Dummies",year:1993,q:"Mmm Mmm Mmm Crash Test Dummies"},
  {id:400,title:"Linger",artist:"The Cranberries",year:1993,q:"Linger Cranberries"},
  {id:401,title:"Don't Look Back in Anger",artist:"Oasis",year:1996,q:"Dont Look Back in Anger Oasis"},
  {id:402,title:"Champagne Supernova",artist:"Oasis",year:1996,q:"Champagne Supernova Oasis"},
  {id:403,title:"Song 2",artist:"Blur",year:1997,q:"Song 2 Blur"},
  {id:404,title:"Common People",artist:"Pulp",year:1995,q:"Common People Pulp"},
  {id:405,title:"Bittersweet Symphony",artist:"The Verve",year:1997,q:"Bittersweet Symphony Verve"},
  {id:406,title:"Fake Plastic Trees",artist:"Radiohead",year:1995,q:"Fake Plastic Trees Radiohead"},
  {id:407,title:"Karma Police",artist:"Radiohead",year:1997,q:"Karma Police Radiohead"},
  {id:408,title:"Paranoid Android",artist:"Radiohead",year:1997,q:"Paranoid Android Radiohead"},
  {id:409,title:"My Hero",artist:"Foo Fighters",year:1997,q:"My Hero Foo Fighters"},
  {id:410,title:"Everlong",artist:"Foo Fighters",year:1997,q:"Everlong Foo Fighters"},
  {id:411,title:"1979",artist:"Smashing Pumpkins",year:1995,q:"1979 Smashing Pumpkins"},
  {id:412,title:"Bullet with Butterfly Wings",artist:"Smashing Pumpkins",year:1995,q:"Bullet with Butterfly Wings Smashing Pumpkins"},
  {id:413,title:"Closing Time",artist:"Semisonic",year:1998,q:"Closing Time Semisonic"},
  {id:414,title:"The Freshness",artist:"DJ Jazzy Jeff & Fresh Prince",year:1991,q:"Summertime DJ Jazzy Jeff Fresh Prince"},
  {id:415,title:"Regulate",artist:"Warren G",year:1994,q:"Regulate Warren G"},
  {id:416,title:"Nuthin' but a G Thang",artist:"Dr. Dre",year:1992,q:"Nuthin but a G Thang Dr Dre"},
  {id:417,title:"Gin and Juice",artist:"Snoop Dogg",year:1993,q:"Gin and Juice Snoop Dogg"},
  {id:418,title:"C.R.E.A.M.",artist:"Wu-Tang Clan",year:1993,q:"CREAM Wu Tang Clan"},
  {id:419,title:"Shook Ones Pt. II",artist:"Mobb Deep",year:1995,q:"Shook Ones Mobb Deep"},
  {id:420,title:"Ready or Not",artist:"Fugees",year:1996,q:"Ready or Not Fugees"},
  {id:421,title:"Killing Me Softly",artist:"Fugees",year:1996,q:"Killing Me Softly Fugees"},
  {id:422,title:"Fantasy",artist:"Mariah Carey",year:1995,q:"Fantasy Mariah Carey"},
  {id:423,title:"Always Be My Baby",artist:"Mariah Carey",year:1995,q:"Always Be My Baby Mariah Carey"},
  {id:424,title:"Vision of Love",artist:"Mariah Carey",year:1990,q:"Vision of Love Mariah Carey"},
  {id:425,title:"End of the Road",artist:"Boyz II Men",year:1992,q:"End of the Road Boyz II Men"},
  {id:426,title:"I'll Make Love to You",artist:"Boyz II Men",year:1994,q:"Ill Make Love to You Boyz II Men"},
  {id:427,title:"U Can't Touch This",artist:"MC Hammer",year:1990,q:"U Cant Touch This MC Hammer"},
  {id:428,title:"Ice Ice Baby",artist:"Vanilla Ice",year:1990,q:"Ice Ice Baby Vanilla Ice"},
  {id:429,title:"Gonna Make You Sweat",artist:"C+C Music Factory",year:1990,q:"Gonna Make You Sweat CC Music Factory"},
  {id:430,title:"Insomnia",artist:"Faithless",year:1995,q:"Insomnia Faithless"},
  {id:431,title:"Born Slippy",artist:"Underworld",year:1995,q:"Born Slippy Underworld"},
  {id:432,title:"Around the World",artist:"Daft Punk",year:1997,q:"Around the World Daft Punk"},
  {id:433,title:"Firestarter",artist:"Prodigy",year:1996,q:"Firestarter Prodigy"},
  {id:434,title:"Sandstorm",artist:"Darude",year:1999,q:"Sandstorm Darude"},
  {id:435,title:"Blue (Da Ba Dee)",artist:"Eiffel 65",year:1998,q:"Blue Da Ba Dee Eiffel 65"},
  {id:436,title:"What Is Love",artist:"Haddaway",year:1993,q:"What Is Love Haddaway"},
  {id:437,title:"Macarena",artist:"Los del Rio",year:1995,q:"Macarena Los del Rio"},
  {id:438,title:"Mambo No. 5",artist:"Lou Bega",year:1999,q:"Mambo No 5 Lou Bega"},
  {id:439,title:"Ms. Jackson",artist:"OutKast",year:2000,q:"Ms Jackson OutKast"},
  {id:440,title:"Stacy's Mom",artist:"Fountains of Wayne",year:2003,q:"Stacys Mom Fountains of Wayne"},
  {id:441,title:"The Middle",artist:"Jimmy Eat World",year:2001,q:"The Middle Jimmy Eat World"},
  {id:442,title:"Fat Lip",artist:"Sum 41",year:2001,q:"Fat Lip Sum 41"},
  {id:443,title:"All the Small Things",artist:"Blink-182",year:1999,q:"All the Small Things Blink 182"},
  {id:444,title:"I Miss You",artist:"Blink-182",year:2003,q:"I Miss You Blink 182"},
  {id:445,title:"Sk8er Boi",artist:"Avril Lavigne",year:2002,q:"Sk8er Boi Avril Lavigne"},
  {id:446,title:"Bring Me to Life",artist:"Evanescence",year:2003,q:"Bring Me to Life Evanescence"},
  {id:447,title:"Somewhere Only We Know",artist:"Keane",year:2004,q:"Somewhere Only We Know Keane"},
  {id:448,title:"Take Me Out",artist:"Franz Ferdinand",year:2004,q:"Take Me Out Franz Ferdinand"},
  {id:449,title:"Maps",artist:"Yeah Yeah Yeahs",year:2003,q:"Maps Yeah Yeah Yeahs"},
  {id:450,title:"Naive",artist:"The Kooks",year:2006,q:"Naive Kooks"},
  {id:451,title:"I Bet You Look Good on the Dancefloor",artist:"Arctic Monkeys",year:2005,q:"I Bet You Look Good Arctic Monkeys"},
  {id:452,title:"Do I Wanna Know?",artist:"Arctic Monkeys",year:2013,q:"Do I Wanna Know Arctic Monkeys"},
  {id:453,title:"Sex on Fire",artist:"Kings of Leon",year:2008,q:"Sex on Fire Kings of Leon"},
  {id:454,title:"Decode",artist:"Paramore",year:2008,q:"Decode Paramore"},
  {id:455,title:"Misery Business",artist:"Paramore",year:2007,q:"Misery Business Paramore"},
  {id:456,title:"Sugar, We're Goin Down",artist:"Fall Out Boy",year:2005,q:"Sugar Were Goin Down Fall Out Boy"},
  {id:457,title:"Welcome to the Black Parade",artist:"My Chemical Romance",year:2006,q:"Welcome to the Black Parade My Chemical Romance"},
  {id:458,title:"When You Were Young",artist:"The Killers",year:2006,q:"When You Were Young Killers"},
  {id:459,title:"Chasing Pavements",artist:"Adele",year:2008,q:"Chasing Pavements Adele"},
  {id:460,title:"Valerie",artist:"Amy Winehouse",year:2007,q:"Valerie Amy Winehouse"},
  {id:461,title:"Young Folks",artist:"Peter Bjorn and John",year:2006,q:"Young Folks Peter Bjorn John"},
  {id:462,title:"Get the Party Started",artist:"P!nk",year:2001,q:"Get the Party Started Pink"},
  {id:463,title:"So What",artist:"P!nk",year:2008,q:"So What Pink"},
  {id:464,title:"Raise Your Glass",artist:"P!nk",year:2010,q:"Raise Your Glass Pink"},
  {id:465,title:"Behind These Hazel Eyes",artist:"Kelly Clarkson",year:2005,q:"Behind These Hazel Eyes Kelly Clarkson"},
  {id:466,title:"Unwritten",artist:"Natasha Bedingfield",year:2004,q:"Unwritten Natasha Bedingfield"},
  {id:467,title:"1, 2 Step",artist:"Ciara",year:2004,q:"1 2 Step Ciara"},
  {id:468,title:"Promiscuous",artist:"Nelly Furtado",year:2006,q:"Promiscuous Nelly Furtado"},
  {id:469,title:"SexyBack",artist:"Justin Timberlake",year:2006,q:"SexyBack Justin Timberlake"},
  {id:470,title:"Cry Me a River",artist:"Justin Timberlake",year:2002,q:"Cry Me a River Justin Timberlake"},
  {id:471,title:"Rock Your Body",artist:"Justin Timberlake",year:2003,q:"Rock Your Body Justin Timberlake"},
  {id:472,title:"Beautiful",artist:"Christina Aguilera",year:2002,q:"Beautiful Christina Aguilera"},
  {id:473,title:"Dirrty",artist:"Christina Aguilera",year:2002,q:"Dirrty Christina Aguilera"},
  {id:474,title:"Hot in Herre",artist:"Nelly",year:2002,q:"Hot in Herre Nelly"},
  {id:475,title:"Dilemma",artist:"Nelly ft. Kelly Rowland",year:2002,q:"Dilemma Nelly Kelly Rowland"},
  {id:476,title:"Get Low",artist:"Lil Jon",year:2002,q:"Get Low Lil Jon"},
  {id:477,title:"Right Thurr",artist:"Chingy",year:2003,q:"Right Thurr Chingy"},
  {id:478,title:"Tipsy",artist:"J-Kwon",year:2004,q:"Tipsy J-Kwon"},
  {id:479,title:"Lean Back",artist:"Terror Squad",year:2004,q:"Lean Back Terror Squad"},
  {id:480,title:"Lose Control",artist:"Missy Elliott",year:2005,q:"Lose Control Missy Elliott"},
  {id:481,title:"Grillz",artist:"Nelly",year:2005,q:"Grillz Nelly"},
  {id:482,title:"Temperature",artist:"Sean Paul",year:2005,q:"Temperature Sean Paul"},
  {id:483,title:"A Milli",artist:"Lil Wayne",year:2008,q:"A Milli Lil Wayne"},
  {id:484,title:"Live Your Life",artist:"T.I. ft. Rihanna",year:2008,q:"Live Your Life TI Rihanna"},
  {id:485,title:"Tik Tok",artist:"Kesha",year:2009,q:"Tik Tok Kesha"},
  {id:486,title:"We R Who We R",artist:"Kesha",year:2010,q:"We R Who We R Kesha"},
  {id:487,title:"Grenade",artist:"Bruno Mars",year:2010,q:"Grenade Bruno Mars"},
  {id:488,title:"Just the Way You Are",artist:"Bruno Mars",year:2010,q:"Just the Way You Are Bruno Mars"},
  {id:489,title:"24K Magic",artist:"Bruno Mars",year:2016,q:"24K Magic Bruno Mars"},
  {id:490,title:"That's What I Like",artist:"Bruno Mars",year:2017,q:"Thats What I Like Bruno Mars"},
  {id:491,title:"Treasure",artist:"Bruno Mars",year:2012,q:"Treasure Bruno Mars"},
  {id:492,title:"Super Bass",artist:"Nicki Minaj",year:2011,q:"Super Bass Nicki Minaj"},
  {id:493,title:"Starships",artist:"Nicki Minaj",year:2012,q:"Starships Nicki Minaj"},
  {id:494,title:"Anaconda",artist:"Nicki Minaj",year:2014,q:"Anaconda Nicki Minaj"},
  {id:495,title:"Bang Bang",artist:"Jessie J, Ariana Grande & Nicki Minaj",year:2014,q:"Bang Bang Jessie J Ariana Grande"},
  {id:496,title:"Problem",artist:"Ariana Grande",year:2014,q:"Problem Ariana Grande"},
  {id:497,title:"Into You",artist:"Ariana Grande",year:2016,q:"Into You Ariana Grande"},
  {id:498,title:"No Tears Left to Cry",artist:"Ariana Grande",year:2018,q:"No Tears Left to Cry Ariana Grande"},
  {id:499,title:"Attention",artist:"Charlie Puth",year:2017,q:"Attention Charlie Puth"},
  {id:500,title:"See You Again",artist:"Wiz Khalifa ft. Charlie Puth",year:2015,q:"See You Again Wiz Khalifa Charlie Puth"},
  {id:501,title:"Earned It",artist:"The Weeknd",year:2014,q:"Earned It Weeknd"},
  {id:502,title:"The Hills",artist:"The Weeknd",year:2015,q:"The Hills Weeknd"},
  {id:503,title:"New Rules",artist:"Dua Lipa",year:2017,q:"New Rules Dua Lipa"},
  {id:504,title:"IDGAF",artist:"Dua Lipa",year:2018,q:"IDGAF Dua Lipa"},
  {id:505,title:"Psycho",artist:"Post Malone",year:2018,q:"Psycho Post Malone"},
  {id:506,title:"Congratulations",artist:"Post Malone",year:2017,q:"Congratulations Post Malone"},
  {id:507,title:"Circles",artist:"Post Malone",year:2019,q:"Circles Post Malone"},
  {id:508,title:"XO Tour Llif3",artist:"Lil Uzi Vert",year:2017,q:"XO Tour Llif3 Lil Uzi Vert"},
  {id:509,title:"SICKO MODE",artist:"Travis Scott",year:2018,q:"SICKO MODE Travis Scott"},
  {id:510,title:"Goosebumps",artist:"Travis Scott",year:2016,q:"Goosebumps Travis Scott"},
  {id:511,title:"Mo Bamba",artist:"Sheck Wes",year:2018,q:"Mo Bamba Sheck Wes"},
  {id:512,title:"Lucid Dreams",artist:"Juice WRLD",year:2018,q:"Lucid Dreams Juice WRLD"},
  {id:513,title:"Ransom",artist:"Lil Tecca",year:2019,q:"Ransom Lil Tecca"},
  {id:514,title:"ROXANNE",artist:"Arizona Zervas",year:2019,q:"ROXANNE Arizona Zervas"},
  {id:515,title:"Panini",artist:"Lil Nas X",year:2019,q:"Panini Lil Nas X"},
  {id:516,title:"Happier",artist:"Marshmello ft. Bastille",year:2018,q:"Happier Marshmello Bastille"},
  {id:517,title:"Alone",artist:"Marshmello",year:2016,q:"Alone Marshmello"},
  {id:518,title:"Faded",artist:"Alan Walker",year:2015,q:"Faded Alan Walker"},
  {id:519,title:"Waiting for Love",artist:"Avicii",year:2015,q:"Waiting for Love Avicii"},
  {id:520,title:"Animals",artist:"Martin Garrix",year:2013,q:"Animals Martin Garrix"},
  {id:521,title:"Don't Let Me Down",artist:"The Chainsmokers",year:2016,q:"Dont Let Me Down Chainsmokers"},
  {id:522,title:"Roses",artist:"The Chainsmokers",year:2015,q:"Roses Chainsmokers"},
  {id:523,title:"All of Me",artist:"John Legend",year:2013,q:"All of Me John Legend"},
  {id:524,title:"Photograph",artist:"Ed Sheeran",year:2014,q:"Photograph Ed Sheeran"},
  {id:525,title:"Perfect",artist:"Ed Sheeran",year:2017,q:"Perfect Ed Sheeran"},
  {id:526,title:"Castle on the Hill",artist:"Ed Sheeran",year:2017,q:"Castle on the Hill Ed Sheeran"},
  {id:527,title:"Heathens",artist:"Twenty One Pilots",year:2016,q:"Heathens Twenty One Pilots"},
  {id:528,title:"Ride",artist:"Twenty One Pilots",year:2015,q:"Ride Twenty One Pilots"},
  {id:529,title:"Believer",artist:"Imagine Dragons",year:2017,q:"Believer Imagine Dragons"},
  {id:530,title:"Demons",artist:"Imagine Dragons",year:2012,q:"Demons Imagine Dragons"},
  {id:531,title:"Whatever It Takes",artist:"Imagine Dragons",year:2017,q:"Whatever It Takes Imagine Dragons"},
  {id:532,title:"Mood",artist:"24kGoldn",year:2020,q:"Mood 24kGoldn"},
  {id:533,title:"Rockstar",artist:"DaBaby",year:2020,q:"Rockstar DaBaby"},
  {id:534,title:"Savage",artist:"Megan Thee Stallion",year:2020,q:"Savage Megan Thee Stallion"},
  {id:535,title:"WAP",artist:"Cardi B ft. Megan Thee Stallion",year:2020,q:"WAP Cardi B"},
  {id:536,title:"Deja Vu",artist:"Olivia Rodrigo",year:2021,q:"Deja Vu Olivia Rodrigo"},
  {id:537,title:"brutal",artist:"Olivia Rodrigo",year:2021,q:"brutal Olivia Rodrigo"},
  {id:538,title:"Beggin'",artist:"Måneskin",year:2021,q:"Beggin Maneskin"},
  {id:539,title:"MAMMAMIA",artist:"Måneskin",year:2021,q:"MAMMAMIA Maneskin"},
  {id:540,title:"Shivers",artist:"Ed Sheeran",year:2021,q:"Shivers Ed Sheeran"},
  {id:541,title:"Bad Habits",artist:"Ed Sheeran",year:2021,q:"Bad Habits Ed Sheeran"},
  {id:542,title:"Physical",artist:"Dua Lipa",year:2020,q:"Physical Dua Lipa"},
  {id:543,title:"Break My Soul",artist:"Beyoncé",year:2022,q:"Break My Soul Beyonce"},
  {id:544,title:"Cuff It",artist:"Beyoncé",year:2022,q:"Cuff It Beyonce"},
  {id:545,title:"Late Night Talking",artist:"Harry Styles",year:2022,q:"Late Night Talking Harry Styles"},
  {id:546,title:"Under the Influence",artist:"Chris Brown",year:2022,q:"Under the Influence Chris Brown"},
  {id:547,title:"Calm Down",artist:"Rema & Selena Gomez",year:2022,q:"Calm Down Rema Selena Gomez"},
  {id:548,title:"I Ain't Worried",artist:"OneRepublic",year:2022,q:"I Aint Worried OneRepublic"},
  {id:549,title:"Left and Right",artist:"Charlie Puth ft. Jung Kook",year:2022,q:"Left and Right Charlie Puth Jung Kook"},
  {id:550,title:"Glimpse of Us",artist:"Joji",year:2022,q:"Glimpse of Us Joji"},
  {id:551,title:"Boy's a Liar",artist:"PinkPantheress & Ice Spice",year:2023,q:"Boys a Liar PinkPantheress Ice Spice"},
  {id:552,title:"Cupid",artist:"FIFTY FIFTY",year:2023,q:"Cupid FIFTY FIFTY"},
  {id:553,title:"Creepin'",artist:"Metro Boomin ft. The Weeknd",year:2022,q:"Creepin Metro Boomin Weeknd"},
  {id:554,title:"Last Last",artist:"Burna Boy",year:2022,q:"Last Last Burna Boy"},
  {id:555,title:"Ghost",artist:"Justin Bieber",year:2021,q:"Ghost Justin Bieber"},
  {id:556,title:"Need to Know",artist:"Doja Cat",year:2021,q:"Need to Know Doja Cat"},
  {id:557,title:"Summertime Blues",artist:"Eddie Cochran",year:1958,q:"Summertime Blues Eddie Cochran"},
  {id:558,title:"My Generation",artist:"The Who",year:1965,q:"My Generation The Who"},
  {id:559,title:"Pinball Wizard",artist:"The Who",year:1969,q:"Pinball Wizard The Who"},
  {id:560,title:"Won't Get Fooled Again",artist:"The Who",year:1971,q:"Wont Get Fooled Again The Who"},
  {id:561,title:"Baba O'Riley",artist:"The Who",year:1971,q:"Baba ORiley The Who"},
  {id:562,title:"I Feel Good",artist:"James Brown",year:1965,q:"I Feel Good James Brown"},
  {id:563,title:"Papa's Got a Brand New Bag",artist:"James Brown",year:1965,q:"Papas Got a Brand New Bag James Brown"},
  {id:564,title:"A Change Is Gonna Come",artist:"Sam Cooke",year:1964,q:"A Change Is Gonna Come Sam Cooke"},
  {id:565,title:"Wonderful World",artist:"Sam Cooke",year:1960,q:"Wonderful World Sam Cooke"},
  {id:566,title:"What a Wonderful World",artist:"Louis Armstrong",year:1967,q:"What a Wonderful World Louis Armstrong"},
  {id:567,title:"The Twist",artist:"Chubby Checker",year:1960,q:"The Twist Chubby Checker"},
  {id:568,title:"Nowhere Man",artist:"The Beatles",year:1965,q:"Nowhere Man Beatles"},
  {id:569,title:"Norwegian Wood",artist:"The Beatles",year:1965,q:"Norwegian Wood Beatles"},
  {id:570,title:"Eleanor Rigby",artist:"The Beatles",year:1966,q:"Eleanor Rigby Beatles"},
  {id:571,title:"Strawberry Fields Forever",artist:"The Beatles",year:1967,q:"Strawberry Fields Forever Beatles"},
  {id:572,title:"While My Guitar Gently Weeps",artist:"The Beatles",year:1968,q:"While My Guitar Gently Weeps Beatles"},
  {id:573,title:"(Sittin' On) The Dock of the Bay",artist:"Otis Redding",year:1968,q:"Sitting On The Dock of the Bay Otis Redding"},
  {id:574,title:"Try a Little Tenderness",artist:"Otis Redding",year:1966,q:"Try a Little Tenderness Otis Redding"},
  {id:575,title:"You Can't Hurry Love",artist:"The Supremes",year:1966,q:"You Cant Hurry Love Supremes"},
  {id:576,title:"Stop! In the Name of Love",artist:"The Supremes",year:1965,q:"Stop In the Name of Love Supremes"},
  {id:577,title:"Dancing in the Street",artist:"Martha and the Vandellas",year:1964,q:"Dancing in the Street Martha Vandellas"},
  {id:578,title:"Sunshine of Your Love",artist:"Cream",year:1967,q:"Sunshine of Your Love Cream"},
  {id:579,title:"Piece of My Heart",artist:"Big Brother & The Holding Company",year:1968,q:"Piece of My Heart Janis Joplin"},
  {id:580,title:"Layla",artist:"Derek and the Dominos",year:1970,q:"Layla Derek Dominos Eric Clapton"},
  {id:581,title:"Wonderful Tonight",artist:"Eric Clapton",year:1977,q:"Wonderful Tonight Eric Clapton"},
  {id:582,title:"Tears in Heaven",artist:"Eric Clapton",year:1992,q:"Tears in Heaven Eric Clapton"},
  {id:583,title:"Piano Man",artist:"Billy Joel",year:1973,q:"Piano Man Billy Joel"},
  {id:584,title:"Vienna",artist:"Billy Joel",year:1977,q:"Vienna Billy Joel"},
  {id:585,title:"Scenes from an Italian Restaurant",artist:"Billy Joel",year:1977,q:"Scenes from an Italian Restaurant Billy Joel"},
  {id:586,title:"Uptown Girl",artist:"Billy Joel",year:1983,q:"Uptown Girl Billy Joel"},
  {id:587,title:"Ziggy Stardust",artist:"David Bowie",year:1972,q:"Ziggy Stardust David Bowie"},
  {id:588,title:"Heroes",artist:"David Bowie",year:1977,q:"Heroes David Bowie"},
  {id:589,title:"Space Oddity",artist:"David Bowie",year:1969,q:"Space Oddity David Bowie"},
  {id:590,title:"Let's Dance",artist:"David Bowie",year:1983,q:"Lets Dance David Bowie"},
  {id:591,title:"Changes",artist:"David Bowie",year:1971,q:"Changes David Bowie"},
  {id:592,title:"Starman",artist:"David Bowie",year:1972,q:"Starman David Bowie"},
  {id:593,title:"Life on Mars?",artist:"David Bowie",year:1971,q:"Life on Mars David Bowie"},
  {id:594,title:"Get Up, Stand Up",artist:"Bob Marley",year:1973,q:"Get Up Stand Up Bob Marley"},
  {id:595,title:"Could You Be Loved",artist:"Bob Marley",year:1980,q:"Could You Be Loved Bob Marley"},
  {id:596,title:"Redemption Song",artist:"Bob Marley",year:1980,q:"Redemption Song Bob Marley"},
  {id:597,title:"Is This Love",artist:"Bob Marley",year:1978,q:"Is This Love Bob Marley"},
  {id:598,title:"Three Little Birds",artist:"Bob Marley",year:1977,q:"Three Little Birds Bob Marley"},
  {id:599,title:"Gimme! Gimme! Gimme!",artist:"ABBA",year:1979,q:"Gimme Gimme Gimme ABBA"},
  {id:600,title:"Mamma Mia",artist:"ABBA",year:1975,q:"Mamma Mia ABBA"},
  {id:601,title:"S.O.S.",artist:"ABBA",year:1975,q:"SOS ABBA"},
  {id:602,title:"Fernando",artist:"ABBA",year:1976,q:"Fernando ABBA"},
  {id:603,title:"The Winner Takes It All",artist:"ABBA",year:1980,q:"Winner Takes It All ABBA"},
  {id:604,title:"Knowing Me, Knowing You",artist:"ABBA",year:1977,q:"Knowing Me Knowing You ABBA"},
  {id:605,title:"Super Trouper",artist:"ABBA",year:1980,q:"Super Trouper ABBA"},
  {id:606,title:"Crazy Little Thing Called Love",artist:"Queen",year:1979,q:"Crazy Little Thing Called Love Queen"},
  {id:607,title:"Somebody to Love",artist:"Queen",year:1976,q:"Somebody to Love Queen"},
  {id:608,title:"Radio Ga Ga",artist:"Queen",year:1984,q:"Radio Ga Ga Queen"},
  {id:609,title:"I Want to Break Free",artist:"Queen",year:1984,q:"I Want to Break Free Queen"},
  {id:610,title:"Killer Queen",artist:"Queen",year:1974,q:"Killer Queen Queen"},
  {id:611,title:"Who Wants to Live Forever",artist:"Queen",year:1986,q:"Who Wants to Live Forever Queen"},
  {id:612,title:"You're My Best Friend",artist:"Queen",year:1975,q:"Youre My Best Friend Queen"},
  {id:613,title:"Hot Stuff",artist:"Donna Summer",year:1979,q:"Hot Stuff Donna Summer"},
  {id:614,title:"Last Dance",artist:"Donna Summer",year:1978,q:"Last Dance Donna Summer"},
  {id:615,title:"I Feel Love",artist:"Donna Summer",year:1977,q:"I Feel Love Donna Summer"},
  {id:616,title:"Shining Star",artist:"Earth, Wind & Fire",year:1975,q:"Shining Star Earth Wind Fire"},
  {id:617,title:"After the Love Has Gone",artist:"Earth, Wind & Fire",year:1979,q:"After the Love Has Gone Earth Wind Fire"},
  {id:618,title:"Got to Give It Up",artist:"Marvin Gaye",year:1977,q:"Got to Give It Up Marvin Gaye"},
  {id:619,title:"Sexual Healing",artist:"Marvin Gaye",year:1982,q:"Sexual Healing Marvin Gaye"},
  {id:620,title:"Let's Get It On",artist:"Marvin Gaye",year:1973,q:"Lets Get It On Marvin Gaye"},
  {id:621,title:"What's Going On",artist:"Marvin Gaye",year:1971,q:"Whats Going On Marvin Gaye"},
  {id:622,title:"Dancing Machine",artist:"The Jackson 5",year:1974,q:"Dancing Machine Jackson 5"},
  {id:623,title:"I Want You Back",artist:"The Jackson 5",year:1969,q:"I Want You Back Jackson 5"},
  {id:624,title:"ABC",artist:"The Jackson 5",year:1970,q:"ABC Jackson 5"},
  {id:625,title:"You Give Love a Bad Name",artist:"Bon Jovi",year:1986,q:"You Give Love a Bad Name Bon Jovi"},
  {id:626,title:"Wanted Dead or Alive",artist:"Bon Jovi",year:1986,q:"Wanted Dead or Alive Bon Jovi"},
  {id:627,title:"Here I Go Again",artist:"Whitesnake",year:1987,q:"Here I Go Again Whitesnake"},
  {id:628,title:"Every Rose Has Its Thorn",artist:"Poison",year:1988,q:"Every Rose Has Its Thorn Poison"},
  {id:629,title:"Love Bites",artist:"Def Leppard",year:1987,q:"Love Bites Def Leppard"},
  {id:630,title:"Photograph",artist:"Def Leppard",year:1983,q:"Photograph Def Leppard"},
  {id:631,title:"Sister Christian",artist:"Night Ranger",year:1984,q:"Sister Christian Night Ranger"},
  {id:632,title:"Round and Round",artist:"Ratt",year:1984,q:"Round and Round Ratt"},
  {id:633,title:"Panama",artist:"Van Halen",year:1984,q:"Panama Van Halen"},
  {id:634,title:"Hot for Teacher",artist:"Van Halen",year:1984,q:"Hot for Teacher Van Halen"},
  {id:635,title:"Runnin' with the Devil",artist:"Van Halen",year:1978,q:"Runnin with the Devil Van Halen"},
  {id:636,title:"You Shook Me All Night Long",artist:"AC/DC",year:1980,q:"You Shook Me All Night Long ACDC"},
  {id:637,title:"Thunderstruck",artist:"AC/DC",year:1990,q:"Thunderstruck ACDC"},
  {id:638,title:"For Those About to Rock",artist:"AC/DC",year:1981,q:"For Those About to Rock ACDC"},
  {id:639,title:"Master of Puppets",artist:"Metallica",year:1986,q:"Master of Puppets Metallica"},
  {id:640,title:"Enter Sandman",artist:"Metallica",year:1991,q:"Enter Sandman Metallica"},
  {id:641,title:"Nothing Else Matters",artist:"Metallica",year:1991,q:"Nothing Else Matters Metallica"},
  {id:642,title:"One",artist:"Metallica",year:1988,q:"One Metallica"},
  {id:643,title:"The Trooper",artist:"Iron Maiden",year:1983,q:"The Trooper Iron Maiden"},
  {id:644,title:"Run to the Hills",artist:"Iron Maiden",year:1982,q:"Run to the Hills Iron Maiden"},
  {id:645,title:"Fade to Black",artist:"Metallica",year:1984,q:"Fade to Black Metallica"},
  {id:646,title:"The Number of the Beast",artist:"Iron Maiden",year:1982,q:"Number of the Beast Iron Maiden"},
  {id:647,title:"Walk",artist:"Pantera",year:1992,q:"Walk Pantera"},
  {id:648,title:"Ace of Spades",artist:"Motörhead",year:1980,q:"Ace of Spades Motorhead"},
  {id:649,title:"Head Like a Hole",artist:"Nine Inch Nails",year:1989,q:"Head Like a Hole Nine Inch Nails"},
  {id:650,title:"Closer",artist:"Nine Inch Nails",year:1994,q:"Closer Nine Inch Nails"},
  {id:651,title:"Mad World",artist:"Tears for Fears",year:1982,q:"Mad World Tears for Fears"},
  {id:652,title:"True",artist:"Spandau Ballet",year:1983,q:"True Spandau Ballet"},
  {id:653,title:"Don't You Want Me",artist:"The Human League",year:1981,q:"Dont You Want Me Human League"},
  {id:654,title:"Smalltown Boy",artist:"Bronski Beat",year:1984,q:"Smalltown Boy Bronski Beat"},
  {id:655,title:"Just Can't Get Enough",artist:"Depeche Mode",year:1981,q:"Just Cant Get Enough Depeche Mode"},
  {id:656,title:"Lips Like Sugar",artist:"Echo & the Bunnymen",year:1987,q:"Lips Like Sugar Echo Bunnymen"},
  {id:657,title:"How Soon Is Now?",artist:"The Smiths",year:1984,q:"How Soon Is Now Smiths"},
  {id:658,title:"There Is a Light That Never Goes Out",artist:"The Smiths",year:1986,q:"There Is a Light That Never Goes Out Smiths"},
  {id:659,title:"This Charming Man",artist:"The Smiths",year:1983,q:"This Charming Man Smiths"},
  {id:660,title:"Boys Don't Cry",artist:"The Cure",year:1979,q:"Boys Dont Cry Cure"},
  {id:661,title:"Friday I'm in Love",artist:"The Cure",year:1992,q:"Friday Im in Love Cure"},
  {id:662,title:"Close to Me",artist:"The Cure",year:1985,q:"Close to Me Cure"},
  {id:663,title:"Raspberry Beret",artist:"Prince",year:1985,q:"Raspberry Beret Prince"},
  {id:664,title:"Kiss",artist:"Prince",year:1986,q:"Kiss Prince"},
  {id:665,title:"1999",artist:"Prince",year:1982,q:"1999 Prince"},
  {id:666,title:"Let's Go Crazy",artist:"Prince",year:1984,q:"Lets Go Crazy Prince"},
  {id:667,title:"Little Red Corvette",artist:"Prince",year:1982,q:"Little Red Corvette Prince"},
  {id:668,title:"Where Is My Mind?",artist:"Pixies",year:1988,q:"Where Is My Mind Pixies"},
  {id:669,title:"November Rain",artist:"Guns N' Roses",year:1991,q:"November Rain Guns N Roses"},
  {id:670,title:"Paradise City",artist:"Guns N' Roses",year:1987,q:"Paradise City Guns N Roses"},
  {id:671,title:"Black",artist:"Pearl Jam",year:1991,q:"Black Pearl Jam"},
  {id:672,title:"Yellow Ledbetter",artist:"Pearl Jam",year:1992,q:"Yellow Ledbetter Pearl Jam"},
  {id:673,title:"Come as You Are",artist:"Nirvana",year:1991,q:"Come as You Are Nirvana"},
  {id:674,title:"Lithium",artist:"Nirvana",year:1991,q:"Lithium Nirvana"},
  {id:675,title:"In Bloom",artist:"Nirvana",year:1991,q:"In Bloom Nirvana"},
  {id:676,title:"All Apologies",artist:"Nirvana",year:1993,q:"All Apologies Nirvana"},
  {id:677,title:"My Own Worst Enemy",artist:"Lit",year:1999,q:"My Own Worst Enemy Lit"},
  {id:678,title:"Inside Out",artist:"Eve 6",year:1998,q:"Inside Out Eve 6"},
  {id:679,title:"Fly",artist:"Sugar Ray",year:1997,q:"Fly Sugar Ray"},
  {id:680,title:"Every Morning",artist:"Sugar Ray",year:1999,q:"Every Morning Sugar Ray"},
  {id:681,title:"Walkin' on the Sun",artist:"Smash Mouth",year:1997,q:"Walkin on the Sun Smash Mouth"},
  {id:682,title:"Steal My Sunshine",artist:"Len",year:1999,q:"Steal My Sunshine Len"},
  {id:683,title:"One Headlight",artist:"The Wallflowers",year:1996,q:"One Headlight Wallflowers"},
  {id:684,title:"Jumper",artist:"Third Eye Blind",year:1997,q:"Jumper Third Eye Blind"},
  {id:685,title:"How's It Going to Be",artist:"Third Eye Blind",year:1997,q:"Hows It Going to Be Third Eye Blind"},
  {id:686,title:"Machinehead",artist:"Bush",year:1994,q:"Machinehead Bush"},
  {id:687,title:"The Impression That I Get",artist:"Mighty Mighty Bosstones",year:1997,q:"Impression That I Get Mighty Mighty Bosstones"},
  {id:688,title:"Sell Out",artist:"Reel Big Fish",year:1996,q:"Sell Out Reel Big Fish"},
  {id:689,title:"Flagpole Sitta",artist:"Harvey Danger",year:1997,q:"Flagpole Sitta Harvey Danger"},
  {id:690,title:"Sex and Candy",artist:"Marcy Playground",year:1997,q:"Sex and Candy Marcy Playground"},
  {id:691,title:"Lovefool",artist:"The Cardigans",year:1996,q:"Lovefool Cardigans"},
  {id:692,title:"The Way",artist:"Fastball",year:1998,q:"The Way Fastball"},
  {id:693,title:"Fly Away",artist:"Lenny Kravitz",year:1998,q:"Fly Away Lenny Kravitz"},
  {id:694,title:"Are You Gonna Go My Way",artist:"Lenny Kravitz",year:1993,q:"Are You Gonna Go My Way Lenny Kravitz"},
  {id:695,title:"You Oughta Know",artist:"Alanis Morissette",year:1995,q:"You Oughta Know Alanis Morissette"},
  {id:696,title:"Ironic",artist:"Alanis Morissette",year:1995,q:"Ironic Alanis Morissette"},
  {id:697,title:"Hand in My Pocket",artist:"Alanis Morissette",year:1995,q:"Hand in My Pocket Alanis Morissette"},
  {id:698,title:"Criminal",artist:"Fiona Apple",year:1996,q:"Criminal Fiona Apple"},
  {id:699,title:"Kiss Me",artist:"Sixpence None the Richer",year:1997,q:"Kiss Me Sixpence None the Richer"},
  {id:700,title:"I Don't Want to Miss a Thing",artist:"Aerosmith",year:1998,q:"I Dont Want to Miss a Thing Aerosmith"},
  {id:701,title:"Genie in a Bottle",artist:"Christina Aguilera",year:1999,q:"Genie in a Bottle Christina Aguilera"},
  {id:702,title:"Pony",artist:"Ginuwine",year:1996,q:"Pony Ginuwine"},
  {id:703,title:"Poison",artist:"Bell Biv DeVoe",year:1990,q:"Poison Bell Biv DeVoe"},
  {id:704,title:"This Is How We Do It",artist:"Montell Jordan",year:1995,q:"This Is How We Do It Montell Jordan"},
  {id:705,title:"Gettin' Jiggy wit It",artist:"Will Smith",year:1997,q:"Gettin Jiggy wit It Will Smith"},
  {id:706,title:"Miami",artist:"Will Smith",year:1998,q:"Miami Will Smith"},
  {id:707,title:"Hard Knock Life",artist:"Jay-Z",year:1998,q:"Hard Knock Life Jay Z"},
  {id:708,title:"Juicy",artist:"The Notorious B.I.G.",year:1994,q:"Juicy Notorious BIG"},
  {id:709,title:"Changes",artist:"2Pac",year:1998,q:"Changes 2Pac"},
  {id:710,title:"Dear Mama",artist:"2Pac",year:1995,q:"Dear Mama 2Pac"},
  {id:711,title:"Passin' Me By",artist:"The Pharcyde",year:1992,q:"Passin Me By Pharcyde"},
  {id:712,title:"Rosa Parks",artist:"OutKast",year:1998,q:"Rosa Parks OutKast"},
  {id:713,title:"Crazy Train",artist:"Ozzy Osbourne",year:1980,q:"Crazy Train Ozzy Osbourne"},
  {id:714,title:"The Reason",artist:"Hoobastank",year:2003,q:"The Reason Hoobastank"},
  {id:715,title:"Kryptonite",artist:"3 Doors Down",year:2000,q:"Kryptonite 3 Doors Down"},
  {id:716,title:"It's Been Awhile",artist:"Staind",year:2001,q:"Its Been Awhile Staind"},
  {id:717,title:"Crawling",artist:"Linkin Park",year:2000,q:"Crawling Linkin Park"},
  {id:718,title:"Faint",artist:"Linkin Park",year:2003,q:"Faint Linkin Park"},
  {id:719,title:"What I've Done",artist:"Linkin Park",year:2007,q:"What Ive Done Linkin Park"},
  {id:720,title:"Holiday",artist:"Green Day",year:2004,q:"Holiday Green Day"},
  {id:721,title:"American Idiot",artist:"Green Day",year:2004,q:"American Idiot Green Day"},
  {id:722,title:"21 Guns",artist:"Green Day",year:2009,q:"21 Guns Green Day"},
  {id:723,title:"Best of You",artist:"Foo Fighters",year:2005,q:"Best of You Foo Fighters"},
  {id:724,title:"The Pretender",artist:"Foo Fighters",year:2007,q:"The Pretender Foo Fighters"},
  {id:725,title:"Learn to Fly",artist:"Foo Fighters",year:1999,q:"Learn to Fly Foo Fighters"},
  {id:726,title:"Times Like These",artist:"Foo Fighters",year:2002,q:"Times Like These Foo Fighters"},
  {id:727,title:"Chop Suey!",artist:"System of a Down",year:2001,q:"Chop Suey System of a Down"},
  {id:728,title:"Toxicity",artist:"System of a Down",year:2001,q:"Toxicity System of a Down"},
  {id:729,title:"B.Y.O.B.",artist:"System of a Down",year:2005,q:"BYOB System of a Down"},
  {id:730,title:"Last Resort",artist:"Papa Roach",year:2000,q:"Last Resort Papa Roach"},
  {id:731,title:"Bodies",artist:"Drowning Pool",year:2001,q:"Bodies Drowning Pool"},
  {id:732,title:"Headstrong",artist:"Trapt",year:2002,q:"Headstrong Trapt"},
  {id:733,title:"Clint Eastwood",artist:"Gorillaz",year:2001,q:"Clint Eastwood Gorillaz"},
  {id:734,title:"Harder, Better, Faster, Stronger",artist:"Daft Punk",year:2001,q:"Harder Better Faster Stronger Daft Punk"},
  {id:735,title:"One More Time",artist:"Daft Punk",year:2000,q:"One More Time Daft Punk"},
  {id:736,title:"Hey Mama",artist:"Black Eyed Peas",year:2003,q:"Hey Mama Black Eyed Peas"},
  {id:737,title:"Where Is the Love?",artist:"Black Eyed Peas",year:2003,q:"Where Is the Love Black Eyed Peas"},
  {id:738,title:"My Humps",artist:"Black Eyed Peas",year:2005,q:"My Humps Black Eyed Peas"},
  {id:739,title:"Milkshake",artist:"Kelis",year:2003,q:"Milkshake Kelis"},
  {id:740,title:"Hollaback Girl",artist:"Gwen Stefani",year:2004,q:"Hollaback Girl Gwen Stefani"},
  {id:741,title:"Rich Girl",artist:"Gwen Stefani",year:2004,q:"Rich Girl Gwen Stefani"},
  {id:742,title:"Oops!... I Did It Again",artist:"Britney Spears",year:2000,q:"Oops I Did It Again Britney Spears"},
  {id:743,title:"Buttons",artist:"Pussycat Dolls",year:2005,q:"Buttons Pussycat Dolls"},
  {id:744,title:"Don't Cha",artist:"Pussycat Dolls",year:2005,q:"Dont Cha Pussycat Dolls"},
  {id:745,title:"Fergalicious",artist:"Fergie",year:2006,q:"Fergalicious Fergie"},
  {id:746,title:"Glamorous",artist:"Fergie",year:2006,q:"Glamorous Fergie"},
  {id:747,title:"Say It Right",artist:"Nelly Furtado",year:2006,q:"Say It Right Nelly Furtado"},
  {id:748,title:"Pon de Replay",artist:"Rihanna",year:2005,q:"Pon de Replay Rihanna"},
  {id:749,title:"Don't Stop the Music",artist:"Rihanna",year:2007,q:"Dont Stop the Music Rihanna"},
  {id:750,title:"Rude Boy",artist:"Rihanna",year:2009,q:"Rude Boy Rihanna"},
  {id:751,title:"Run the World (Girls)",artist:"Beyoncé",year:2011,q:"Run the World Girls Beyonce"},
  {id:752,title:"Irreplaceable",artist:"Beyoncé",year:2006,q:"Irreplaceable Beyonce"},
  {id:753,title:"Halo",artist:"Beyoncé",year:2008,q:"Halo Beyonce"},
  {id:754,title:"Team",artist:"Lorde",year:2013,q:"Team Lorde"},
  {id:755,title:"Green Light",artist:"Lorde",year:2017,q:"Green Light Lorde"},
  {id:756,title:"Habits (Stay High)",artist:"Tove Lo",year:2014,q:"Habits Stay High Tove Lo"},
  {id:757,title:"Lean On",artist:"Major Lazer",year:2015,q:"Lean On Major Lazer"},
  {id:758,title:"Where Are Ü Now",artist:"Jack Ü ft. Justin Bieber",year:2015,q:"Where Are U Now Jack U Justin Bieber"},
  {id:759,title:"What Do You Mean?",artist:"Justin Bieber",year:2015,q:"What Do You Mean Justin Bieber"},
  {id:760,title:"Let Me Love You",artist:"DJ Snake ft. Justin Bieber",year:2016,q:"Let Me Love You DJ Snake Justin Bieber"},
  {id:761,title:"Cold Water",artist:"Major Lazer ft. Justin Bieber",year:2016,q:"Cold Water Major Lazer Justin Bieber"},
  {id:762,title:"Formation",artist:"Beyoncé",year:2016,q:"Formation Beyonce"},
  {id:763,title:"DNA.",artist:"Kendrick Lamar",year:2017,q:"DNA Kendrick Lamar"},
  {id:764,title:"Alright",artist:"Kendrick Lamar",year:2015,q:"Alright Kendrick Lamar"},
  {id:765,title:"Swimming Pools",artist:"Kendrick Lamar",year:2012,q:"Swimming Pools Kendrick Lamar"},
  {id:766,title:"Money Trees",artist:"Kendrick Lamar",year:2012,q:"Money Trees Kendrick Lamar"},
  {id:767,title:"Nice for What",artist:"Drake",year:2018,q:"Nice for What Drake"},
  {id:768,title:"In My Feelings",artist:"Drake",year:2018,q:"In My Feelings Drake"},
  {id:769,title:"Passionfruit",artist:"Drake",year:2017,q:"Passionfruit Drake"},
  {id:770,title:"Started from the Bottom",artist:"Drake",year:2013,q:"Started from the Bottom Drake"},
  {id:771,title:"Hold On, We're Going Home",artist:"Drake",year:2013,q:"Hold On Were Going Home Drake"},
  {id:772,title:"Love Story",artist:"Taylor Swift",year:2008,q:"Love Story Taylor Swift"},
  {id:773,title:"You Belong with Me",artist:"Taylor Swift",year:2009,q:"You Belong with Me Taylor Swift"},
  {id:774,title:"We Are Never Getting Back Together",artist:"Taylor Swift",year:2012,q:"We Are Never Getting Back Together Taylor Swift"},
  {id:775,title:"Style",artist:"Taylor Swift",year:2014,q:"Style Taylor Swift"},
  {id:776,title:"Bad Blood",artist:"Taylor Swift",year:2014,q:"Bad Blood Taylor Swift"},
  {id:777,title:"Look What You Made Me Do",artist:"Taylor Swift",year:2017,q:"Look What You Made Me Do Taylor Swift"},
  {id:778,title:"Delicate",artist:"Taylor Swift",year:2017,q:"Delicate Taylor Swift"},
  {id:779,title:"Cardigan",artist:"Taylor Swift",year:2020,q:"Cardigan Taylor Swift"},
  {id:780,title:"Willow",artist:"Taylor Swift",year:2020,q:"Willow Taylor Swift"},
  {id:781,title:"Lavender Haze",artist:"Taylor Swift",year:2022,q:"Lavender Haze Taylor Swift"},
  {id:782,title:"Midnight Rain",artist:"Taylor Swift",year:2022,q:"Midnight Rain Taylor Swift"},
  {id:783,title:"Fortnight",artist:"Taylor Swift ft. Post Malone",year:2024,q:"Fortnight Taylor Swift Post Malone"},
  {id:784,title:"Please Please Please",artist:"Sabrina Carpenter",year:2024,q:"Please Please Please Sabrina Carpenter"},
  {id:785,title:"Taste",artist:"Sabrina Carpenter",year:2024,q:"Taste Sabrina Carpenter"},
  {id:786,title:"Birds of a Feather",artist:"Billie Eilish",year:2024,q:"Birds of a Feather Billie Eilish"},
  {id:787,title:"Lunch",artist:"Billie Eilish",year:2024,q:"Lunch Billie Eilish"},
  {id:788,title:"Lovely",artist:"Billie Eilish & Khalid",year:2018,q:"Lovely Billie Eilish Khalid"},
  {id:789,title:"Everything I Wanted",artist:"Billie Eilish",year:2019,q:"Everything I Wanted Billie Eilish"},
  {id:790,title:"Happier Than Ever",artist:"Billie Eilish",year:2021,q:"Happier Than Ever Billie Eilish"},
  {id:791,title:"Therefore I Am",artist:"Billie Eilish",year:2020,q:"Therefore I Am Billie Eilish"},
  {id:792,title:"Peach (Cobbler)",artist:"Young Thug",year:2016,q:"Best Friend Young Thug"},
  {id:793,title:"HUMBLE.",artist:"Kendrick Lamar",year:2017,q:"HUMBLE Kendrick Lamar"},
  {id:794,title:"Not Like Us",artist:"Kendrick Lamar",year:2024,q:"Not Like Us Kendrick Lamar"},
  {id:795,title:"Like That",artist:"Future, Metro Boomin & Kendrick Lamar",year:2024,q:"Like That Future Metro Boomin Kendrick Lamar"},
  {id:796,title:"Lose Yourself to Dance",artist:"Daft Punk",year:2013,q:"Lose Yourself to Dance Daft Punk"},
  {id:797,title:"Midnight City",artist:"M83",year:2011,q:"Midnight City M83"},
  {id:798,title:"Somebody Else",artist:"The 1975",year:2016,q:"Somebody Else The 1975"},
  {id:799,title:"Chocolate",artist:"The 1975",year:2013,q:"Chocolate The 1975"},
  {id:800,title:"Robbers",artist:"The 1975",year:2014,q:"Robbers The 1975"},
  {id:801,title:"About You",artist:"The 1975",year:2022,q:"About You The 1975"},
  {id:802,title:"Electric Feel",artist:"MGMT",year:2007,q:"Electric Feel MGMT"},
  {id:803,title:"Kids",artist:"MGMT",year:2007,q:"Kids MGMT"},
  {id:804,title:"Tongue Tied",artist:"Grouplove",year:2011,q:"Tongue Tied Grouplove"},
  {id:805,title:"Sweater Weather",artist:"The Neighbourhood",year:2012,q:"Sweater Weather Neighbourhood"},
  {id:806,title:"R U Mine?",artist:"Arctic Monkeys",year:2012,q:"R U Mine Arctic Monkeys"},
  {id:807,title:"505",artist:"Arctic Monkeys",year:2007,q:"505 Arctic Monkeys"},
  {id:808,title:"Fluorescent Adolescent",artist:"Arctic Monkeys",year:2007,q:"Fluorescent Adolescent Arctic Monkeys"},
  {id:809,title:"Slow Hands",artist:"Niall Horan",year:2017,q:"Slow Hands Niall Horan"},
  {id:810,title:"Pillowtalk",artist:"Zayn",year:2016,q:"Pillowtalk Zayn"},
  {id:811,title:"Sign of the Times",artist:"Harry Styles",year:2017,q:"Sign of the Times Harry Styles"},
  {id:812,title:"Adore You",artist:"Harry Styles",year:2019,q:"Adore You Harry Styles"},
  {id:813,title:"Golden",artist:"Harry Styles",year:2020,q:"Golden Harry Styles"},
  {id:814,title:"Yummy",artist:"Justin Bieber",year:2020,q:"Yummy Justin Bieber"},
  {id:815,title:"Intentions",artist:"Justin Bieber",year:2020,q:"Intentions Justin Bieber"},
  {id:816,title:"Leave the Door Open",artist:"Silk Sonic",year:2021,q:"Leave the Door Open Silk Sonic"},
  {id:817,title:"Smokin Out the Window",artist:"Silk Sonic",year:2021,q:"Smokin Out the Window Silk Sonic"},
  {id:818,title:"Doja",artist:"Central Cee",year:2022,q:"Doja Central Cee"},
  {id:819,title:"Sprinter",artist:"Central Cee & Dave",year:2023,q:"Sprinter Central Cee Dave"},
  {id:820,title:"Stargazing",artist:"Myles Smith",year:2024,q:"Stargazing Myles Smith"},
  {id:821,title:"Beautiful Things",artist:"Benson Boone",year:2024,q:"Beautiful Things Benson Boone"},
  {id:822,title:"Gata Only",artist:"FloyyMenor & Cris MJ",year:2023,q:"Gata Only FloyyMenor Cris MJ"},
  {id:823,title:"Water",artist:"Tyla",year:2023,q:"Water Tyla"},
  {id:824,title:"Greedy",artist:"Tate McRae",year:2023,q:"Greedy Tate McRae"},
  {id:825,title:"Exes",artist:"Tate McRae",year:2024,q:"Exes Tate McRae"},
  {id:826,title:"Houdini",artist:"Eminem",year:2024,q:"Houdini Eminem"},
  {id:827,title:"Guess",artist:"Charli XCX & Billie Eilish",year:2024,q:"Guess Charli XCX Billie Eilish"},
  {id:828,title:"360",artist:"Charli XCX",year:2024,q:"360 Charli XCX"},
  {id:829,title:"Apple",artist:"Charli XCX",year:2024,q:"Apple Charli XCX"},
  {id:830,title:"Good Luck Babe!",artist:"Chappell Roan",year:2024,q:"Good Luck Babe Chappell Roan"},
  {id:831,title:"HOT TO GO!",artist:"Chappell Roan",year:2024,q:"HOT TO GO Chappell Roan"},
  {id:832,title:"Pink Pony Club",artist:"Chappell Roan",year:2020,q:"Pink Pony Club Chappell Roan"},
  {id:833,title:"Too Sweet",artist:"Hozier",year:2024,q:"Too Sweet Hozier"},
  {id:834,title:"Stick Season",artist:"Noah Kahan",year:2022,q:"Stick Season Noah Kahan"},
  {id:835,title:"Die with a Smile",artist:"Lady Gaga & Bruno Mars",year:2024,q:"Die with a Smile Lady Gaga Bruno Mars"},
  {id:836,title:"APT.",artist:"ROSÉ & Bruno Mars",year:2024,q:"APT ROSE Bruno Mars"},
  {id:837,title:"Heartless",artist:"Kanye West",year:2008,q:"Heartless Kanye West"},
  {id:838,title:"Love Lockdown",artist:"Kanye West",year:2008,q:"Love Lockdown Kanye West"},
  {id:839,title:"All of the Lights",artist:"Kanye West",year:2010,q:"All of the Lights Kanye West"},
  {id:840,title:"Runaway",artist:"Kanye West",year:2010,q:"Runaway Kanye West"},
  {id:841,title:"Power",artist:"Kanye West",year:2010,q:"Power Kanye West"},
  {id:842,title:"Flashing Lights",artist:"Kanye West",year:2007,q:"Flashing Lights Kanye West"},
];

module.exports = SONGS;
